### ISSUE TITLE
Error occurs installing PYTTSX3 

### ISSUE THREAD

**Issue by hacker2909** [nateshmbhat/pyttsx3#101]
ERROR: Command errored out with exit status 1:
     command: 'c:\users\adish\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\adish\\AppData\\Local\\Temp\\pip-install-t2laoanb\\pyobjc-framework-InputMethodKit\\setup.py'"'"'; __file__='"'"'C:\\Users\\adish\\AppData\\Local\\Temp\\pip-install-t2laoanb\\pyobjc-framework-InputMethodKit\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\adish\AppData\Local\Temp\pip-install-t2laoanb\pyobjc-framework-InputMethodKit\pip-egg-info'
         cwd: C:\Users\adish\AppData\Local\Temp\pip-install-t2laoanb\pyobjc-framework-InputMethodKit\
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\adish\AppData\Local\Temp\pip-install-t2laoanb\pyobjc-framework-InputMethodKit\setup.py", line 21, in <module>
        Extension(
      File "C:\Users\adish\AppData\Local\Temp\pip-install-t2laoanb\pyobjc-framework-InputMethodKit\pyobjc_setup.py", line 408, in Extension
        os_level = get_os_level()
      File "C:\Users\adish\AppData\Local\Temp\pip-install-t2laoanb\pyobjc-framework-InputMethodKit\pyobjc_setup.py", line 218, in get_os_level
        pl = plistlib.readPlist("/System/Library/CoreServices/SystemVersion.plist")
      File "c:\users\adish\appdata\local\programs\python\python38\lib\plistlib.py", line 99, in readPlist
        with _maybe_open(pathOrFile, 'rb') as fp:
      File "c:\users\adish\appdata\local\programs\python\python38\lib\contextlib.py", line 113, in __enter__
        return next(self.gen)
      File "c:\users\adish\appdata\local\programs\python\python38\lib\plistlib.py", line 82, in _maybe_open
        with open(pathOrFile, mode) as fp:
    FileNotFoundError: [Errno 2] No such file or directory: '/System/Library/CoreServices/SystemVersion.plist'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
![ERROR](https://user-images.githubusercontent.com/59710489/76774480-f8e3fd80-67c9-11ea-962e-ec12d68458b7.PNG)

**Comment by necromuralist** [comment]
I get this error too (on Ubuntu 19.10). I don't know why but sometimes installing it gives a different error saying ``PyObjC requires MacOS to build``. [pyobjc](https://pyobjc.readthedocs.io/en/latest/) looks like it's an objective-C bridge.

**Comment by thesantoshprajapati** [comment]
hmm same error i am also getting

**Comment by developerhb** [comment]
I am also getting the same error. Please solve this error as soon as possible

**Comment by developerhb** [comment]
I also figured out that this problem occurs in the latest version. I installed pyttsx3 version 2.7 and there where no errors. So, I request the maintainers of this project to have a look at the latest version. I don't know from which version this error starts. But it is present in the latest version. 

You can temporarily work with version 2.7. Just run this command,
`pip install pyttsx3==2.7  `

**Comment by thesantoshprajapati** [comment]
hmm it worked

**Comment by nateshmbhat** [comment]
@thesantoshprajapati can u please try installing 2.80 or 2.81 and see if they are working ?

**Comment by amerizalde** [comment]
I had the same issue using "pip install pyttsx3". Tried it with "==2.81" and it installed just fine.

**Comment by nateshmbhat** [comment]
OK I will revert back to commit corresponding to 2.81

**Comment by nateshmbhat** [comment]
I have applied the fix for this issue : Latest release is 2.87.
Just install the latest release with `pip install pyttsx3` and please let me know if it fixed the issue.

**Comment by gurleen-kaur-30** [comment]
I tried installing the latest release. The error goes away but another KeyError occurs. This is the error : 
File "<user>/.local/lib/python3.6/site-packages/pyttsx3/__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "/usr/lib/python3.6/weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: None

**Comment by nateshmbhat** [comment]
This might be related to right engine driver not being found 🤔

**Comment by fagunti** [comment]
SyntaxError: invalid syntax
>>> pip install pyttsx3
  File "<stdin>", line 1
    pip install pyttsx3
        ^
SyntaxError: invalid syntax
>>>
,,,,plz help me

**Comment by XxDeDShoTxX** [comment]
It needs python 3.6 or lower
