### ISSUE TITLE
Is there a way to use the espeak-ng engine?

### ISSUE THREAD

**Issue by badVibes--** [nateshmbhat/pyttsx3#103]
I would like to use espeak-ng because it has more languages. Specifically Slovenian. Is there any way i could do that?

**Comment by Epicalert** [comment]
For now can make it use espeak-ng with a symlink:
`sudo ln -s /usr/lib/libespeak-ng.so.1 /usr/lib/libespeak.so.1`

Maybe in the future the library could look for `libespeak-ng` and fall back to `libespeak` if espeak-ng is not installed?

**Comment by TotallyAProgrammer** [comment]
If there is still interest in this, I think I know of a way to implement this without changing a lot of code.

**Comment by TotallyAProgrammer** [comment]
I've pushed a potential implementation to my fork. I'm currently setting up a VM to test this in to see if this basic implementation works. If this works I will go ahead and clean up the code if needed and create a pull request

**Comment by TotallyAProgrammer** [comment]
I'm opening a PR now. I've tested the code and everything appears to be working the way it should.
