### ISSUE TITLE
License Violation?

### ISSUE THREAD

**Issue by kaptainkommie** [nateshmbhat/pyttsx3#108]
@nateshmbhat So it looks like this project is an unacknowledged fork of pyttsx, and might be in violation of its license from https://github.com/RapidWareTech/pyttsx/blob/master/LICENSE

**Comment by nateshmbhat** [comment]
yes , this project uses that project's code at certain points. I can acknoledge the author of that project in  the license of this project. will do that change

**Comment by nateshmbhat** [comment]
This uses GPL3 license that helps the free software community better. Also that referenced project was an old project and has not been maintained since many years.

**Comment by nateshmbhat** [comment]
This is a seperate port of pyttsx in python3. I don't think its a violation. Anyway , I have added credits to the author of pyttsx also in the licence.
Thanks for your help 😃
