### ISSUE TITLE
windows10  pyttsx3.init  -> sap15.py -.>win32com -> DLL load failed 

### ISSUE THREAD

**Issue by nickums** [nateshmbhat/pyttsx3#13]
After reviewing the issues, I have just done the following: in sequence:
install Python36, install pyinstaller,  install pypiwin32, install pyttsx3            
Disappointingly, pyttsx3.init()   fails  as follows -
 ......
  File "C:\Python\Python35\lib\site-packages\pyttsx3\drivers\sapi5.py", line 3, in <module>
    import win32com.client
  File "C:\Python\Python35\lib\site-packages\win32com\__init__.py", line 5, in <module>
    import win32api, sys, os
ImportError: DLL load failed: %1 is not a valid Win32 application.

Help wanted!

**Comment by Kerang** [comment]
[fixed / workaround for pyttsx3 test won't work once compiled with pyinstaller](https://github.com/pyinstaller/pyinstaller/issues/3268)

and

[pyttsx3 fails to execute when compiled](https://github.com/nateshmbhat/pyttsx3/issues/6)

Fix is to create a hook for pyttsx3 in pyinstaller hooks folder and keep pyi_rth_win32comgenpy.py from running on python >= v3.

**Comment by nickums** [comment]
Thanks!  applied your fix and it now works perfectly. very satisfied that it  uses the Windows default  sapi15 voice MARY  rather than the rather robotic espeak.
