### ISSUE TITLE
No Output on Raspberry Pi after restart

### ISSUE THREAD

**Issue by whogben** [nateshmbhat/pyttsx3#134]
I am having trouble getting pyttsx3 to produce any sound output.

After setting it up on my raspberry pi, it was working great. The example code played audio and I could modify it and keep playing audio.

Later, I restarted the raspberry pi, and now there's no audio. No error prints, and it does wait the appropriate amount of time after calling runAndWait(), but there's no sound.

I've used the terminal command "speaker-test" to confirm the speaker is working normally - the audio option in the Raspberry Pi menu shows the correct speaker. I just can't figure out why there's no more output from pyttsx3 when there was before.

The only configuration change was to connect two new items to GPIO pins, I've tried restarting multiple times with those items disconnected without luck.

Any way I can get more debug info / manually specify more info to try and get pyttsx3 to produce sound again?  Many thanks in advance for your suggestions!

**Comment by mustious** [comment]
try checking if audio volumes is 0 with the below command...
`sudo alsamixer`
