### ISSUE TITLE
pyttsx3 is not working in window 10

### ISSUE THREAD

**Issue by mrsuperman001** [nateshmbhat/pyttsx3#137]
I have this error when I try to speak a text.

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/pyttsx3/__init__.py in init(driverName, debug)
     19     try:
---> 20         eng = _activeEngines[driverName]
     21     except KeyError:

15 frames
KeyError: None

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
/usr/lib/python3.6/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    346 
    347         if handle is None:
--> 348             self._handle = _dlopen(self._name, mode)
    349         else:
    350             self._handle = handle

OSError: libespeak.so.1: cannot open shared object file: No such file or directory

Anyone know how to fix it?

**Comment by akchhayalok** [comment]
Try installing sapi5 as for windows machine it uses this driver.
You can install it by 
```
pip install sapi
```

**Comment by willwade** [comment]
Should be fixed.
