### ISSUE TITLE
segmentation fault when the string to be said is empty

### ISSUE THREAD

**Issue by Feargan** [nateshmbhat/pyttsx3#140]
> s = pyttsx3.init()
> s.say('')
> s.runAndWait()

The console of course yields `Segmentation fault`.
I work on Raspbian, Python3.7. Pytt3sx was installed by pip.
`eSpeak text-to-speech: 1.48.03  04.Mar.14`

**Comment by akchhayalok** [comment]
Hi @nateshmbhat 

Can we check for text argument if that's empty then we can display proper message instead of segmentaion fault.

**Comment by nateshmbhat** [comment]
Is this issue fixed @akchhayalok. Did u test it with ur PR ?

**Comment by akchhayalok** [comment]
Is the issue fixed @Feargan

**Comment by nateshmbhat** [comment]
Closing till response
