### ISSUE TITLE
I fixed perfect !

### ISSUE THREAD

**Issue by LuckyYang888** [nateshmbhat/pyttsx3#144]
I tried it and suppirse ! it is ok ! fixed ok ! Tks ! @developerhb !

You can temporarily work with version 2.7. Just run this command,
`pip install pyttsx3==2.7  `

_Originally posted by @developerhb in https://github.com/nateshmbhat/pyttsx3/issues/101#issuecomment-603686821_

**Comment by developerhb** [comment]
> I tried it and suppirse ! it is ok ! fixed ok ! Tks ! @developerhb !
> 
> You can temporarily work with version 2.7. Just run this command,
> `pip install pyttsx3==2.7 `
> 
> _Originally posted by @developerhb in [#101 (comment)](https://github.com/nateshmbhat/pyttsx3/issues/101#issuecomment-603686821)_

@LuckyYang888 
I am glad you find it helpful :smiley:
