### ISSUE TITLE
I cant use it normally in termux 

### ISSUE THREAD

**Issue by BADSHA-36** [nateshmbhat/pyttsx3#150]

**Comment by BADSHA-36** [comment]
I got this issue ![Screenshot_2020-10-16-15-27-40-37.png](https://user-images.githubusercontent.com/68543287/96271888-0fb23300-0feb-11eb-8de7-09f5b14a1b83.png)

**Comment by Deadiy** [comment]
got the same error on my "WikiTeller" python script, runs everywhere but not in termux

**Comment by elig0n** [comment]
you need to clone espeak-ng from github, install buildtools and. /configure it with termux usr/ path. it will then require aplay from alsa-utils which isn't yet available in termux.
