### ISSUE TITLE
Couldn't find differences between synthesized voices of default, en, en_gb, northern_eng, scottish_eng

### ISSUE THREAD

**Issue by sriharsha0806** [nateshmbhat/pyttsx3#153]
Hi all, 
Thanks for sharing the library. I am trying to synthesize different  English voices using espeak.  But the generated voices are all sounding the same. 
https://drive.google.com/file/d/1yrxrZfwcohzvA6O2isrLrA2EbsdzXUKZ/view?usp=sharing

I mean in terms of accent, voice of the person. May I know what am I doing wrong?

**Comment by willwade** [comment]
Nb. This is espeak. Not our bag really here.
