### ISSUE TITLE
pyttsx3 on linux

### ISSUE THREAD

**Issue by Amarnath1904** [nateshmbhat/pyttsx3#156]
this is my code of the python program:

```
import pyttsx3

engin = pyttsx3.init()
engin.say("hello")
engin.runAndWait()
```

output is:

> sh: 1: aplay: not found  

please help me to get out of this error

**Comment by mustious** [comment]
seems you probably don't have alsa-utils. To install alsa-utils...
`sudo apt-get install alsa-utils`

**Comment by Potaziio** [comment]
> seems you probably don't have alsa-utils. To install alsa-utils...
> `sudo apt-get install alsa-utils`

Thanks this worked for me
