### ISSUE TITLE
pyttsx3 breaks Windows 10 sound

### ISSUE THREAD

**Issue by ricardo-reis-1970** [nateshmbhat/pyttsx3#159]
I am using `pyttsx3` on Windows 10 Home on a Dell XPS 13 9370. After running a few times, Windows' default speakers stop producing any sound. The system "thinks" everything is OK, the troubleshooter is as useful as a bicycle under the sea and all the sound alternatives -- bluetooth earplugs, bluetooth headset, HDMI monitor speakers -- work fine.

This is my dev environment. The production one seems to be all right, but I don't develop there and testing in production is usually ill-advised. In my case it's double, since I work with medical devices.

I would very much appreciate any assistance.

**Comment by TotallyAProgrammer** [comment]
What audio driver are you using? pyttsx3 does not take exclusive control of the audio device, it merely interfaces with the system speech synthesizer, which is where your issue might lie.
