### ISSUE TITLE
About how to package software

### ISSUE THREAD

**Issue by EEEEEEcho** [nateshmbhat/pyttsx3#16]
I want to package my program but I have some questions.
such as these
![in cl15c c 5c5ov7mu 9e](https://user-images.githubusercontent.com/30794732/37716640-efd3c434-2d59-11e8-8a38-5b59c0908f46.jpg)
![14 p 8okic3 3 le 1 vq](https://user-images.githubusercontent.com/30794732/37716757-384dd56a-2d5a-11e8-8b8a-4639b9054396.jpg)
And Then I 
![dau lhe4 r8 hyg92sc8ed6](https://user-images.githubusercontent.com/30794732/37716888-81016c72-2d5a-11e8-9302-4c0b6439dea9.jpg)
 meet this trouble
I just want to know what can i do to package it.

**Comment by nateshmbhat** [comment]
issue related to pyinstaller
