### ISSUE TITLE
"save_to_file" does absolutely nothing

### ISSUE THREAD

**Issue by willgf84** [nateshmbhat/pyttsx3#161]
"save_to_file" does absolutely nothing and it is impossible to create the mp3 file.

I am using windows10 and version 2.71, with the following code:

Note: the "engine.say(text)" works perfectly

```
import pyttsx3 
engine = pyttsx3.init()
engine.setProperty("rate", 200)

text = "Hello hello"

engine.say(text)

output_file = "audio.mp3"

engine.save_to_file(text, output_file)
engine.runAndWait()
```

Do you have any ideas to make it work?

**Comment by nateshmbhat** [comment]
duplicate of #142
