### ISSUE TITLE
How to change pitch?

### ISSUE THREAD

**Issue by hyansuper** [nateshmbhat/pyttsx3#164]
espeak is able to set pitch using command line with "-p" parameter  `espeak hello -p 90`

Is pyttsx3 able to set pitch? none of the following works

```python
engine.setProperty('pitch', 90)
engine.setProperty('pitch', '90')
engine.setProperty('p', 90)
engine.setProperty('p', '90')
```

**Comment by TotallyAProgrammer** [comment]
As far as I can tell this is not implemented in the espeak driver for pyttsx3 (yet). If there is a serious demand for this, I might be able to implement a property for it, as pyttsx3's code-base isn't terribly complicated.

**Comment by AbhaydePratap** [comment]
Currently there is no way to set pitch.
I found only these-

`    def setProperty(self, name, value):
        '''
        Adds a property value to set to the event queue. Valid names and values
        include:

        voice: String ID of the voice
        rate: Integer speech rate in words per minute
        volume: Floating point volume of speech in the range [0.0, 1.0]

        Numeric values outside the valid range supported by the driver are
        clipped.

        @param name: Name of the property to fetch
        @type name: str
        @param: Value to set for the property
        @rtype: object
        @raise KeyError: When the property name is unknown
        '''
        self.proxy.setProperty(name, value)`

**Comment by AbhaydePratap** [comment]
Currently there is no way to set pitch.
as in the source code there is option to set Voice, Rate and Volume only
https://github.com/nateshmbhat/pyttsx3/blob/f260013bd8104802328f933c33400856afedbd74/pyttsx3/engine.py#L151-L169

**Comment by TotallyAProgrammer** [comment]
I am currently developing this feature. It should be available soon, as I just have to test it in a few different cases to ensure it still works.

**Comment by TotallyAProgrammer** [comment]
This is now supported ( #173  ) with pyttsx3, this issue can be closed.
