### ISSUE TITLE
what about streamlabs voices ?

### ISSUE THREAD

**Issue by ahmed4end** [nateshmbhat/pyttsx3#166]
what about streamlabs voices ? what about streamlabs voices ? what about streamlabs voices ?

**Comment by TotallyAProgrammer** [comment]
Streamlabs voices would require someone to write a driver for the Streamlabs TTS engine. If Streamlabs uses SAPI5 compatible voices, there might be a way to add the voices to SAPI5, making them accessible by pyttsx3.
