### ISSUE TITLE
pyttsx3.init() NOT WORKING

### ISSUE THREAD

**Issue by LaKhWaN** [nateshmbhat/pyttsx3#167]
I tried literally everything on google youtube etc, but nothing worked i have pypiwin32 and pyaudio. I cam import pyttsx3 but when i do pyttsx3.init()/pyttsx3.init('sapi5') both shows me error No KeyError!

can anyone please help me???

I would be very thankful!

**Comment by asifulmamun** [comment]
Same Problem:
------------
Working in my Windows 10 (64bit) but, When I have cloned this project to my ubuntu 20.4 and installed this pyttsx3 and try to run also this project it's not working.

-Error: http://pastebin.ubuntu.com/p/VTbJprMDnK/

-Python Code: https://pastebin.ubuntu.com/p/tPYzYmmMS6/ (Widows Working but Ubuntu Not working)

**Comment by TotallyAProgrammer** [comment]
@asifulmamun @LaKhWaN **You do not have eSpeak or eSpeak-ng installed. This is a **required** dependency on linux based operating systems.**

**Comment by nateshmbhat** [comment]
Fixed this in master.
