### ISSUE TITLE
pyttsx3.init() not working - big problem - File Added with Pastebin

### ISSUE THREAD

**Issue by asifulmamun** [nateshmbhat/pyttsx3#168]
Working in my Windows 10 (64bit) but, When I have cloned this project to my ubuntu 20.4 and installed this pyttsx3 and try to run also this project it's not working.

-Error: http://pastebin.ubuntu.com/p/VTbJprMDnK/

-Python Code: https://pastebin.ubuntu.com/p/tPYzYmmMS6/ (Widows Working but Ubuntu Not working)

**Comment by ralfiman** [comment]
Man im going trough the same, let me know if u could solve it pls

**Comment by asifulmamun** [comment]
> 
> 
> Man im going trough the same, let me know if u could solve it pls

I'm also waiting for fix this.

**Comment by TotallyAProgrammer** [comment]
@asifulmamun @ralfiman **Please refer to PR #163 This addresses your issue and fixes the error you are having.** If the issue persists, please @ me. eSpeak is no longer supported on most linux distros, they switched to eSpeak-NG.

**Comment by asifulmamun** [comment]
> 
> 
> @asifulmamun @ralfiman **Please refer to PR #163 This addresses your issue and fixes the error you are having.** If the issue persists, please @ me. eSpeak is no longer supported on most linux distros, they switched to eSpeak-NG.

Thanks it's working

**Comment by asifulmamun** [comment]
It solved by espeak and espean-ng depencies. Thanks @TotallyAProgrammer

**Comment by asifulmamun** [comment]
Yah, solved @ralfiman
sudo apt install espeak espeak-ng
