### ISSUE TITLE
Not found module

### ISSUE THREAD

**Issue by marcobaturan** [nateshmbhat/pyttsx3#17]
I pass to python3.6.4, then when I try to run the program in my virtualenv it's send:

python3.6 listen_to_number.py 
Traceback (most recent call last):
  File "listen_to_number.py", line 4, in <module>
    import pyttsx3
ModuleNotFoundError: No module named 'pyttsx3'

**Comment by Kerang** [comment]
The problem isn't with pyttsx3, but that pyinstaller fails to add the pyttsx3 module. I also ran into an issue with another hook causing pyttsx3 not to work. Even after pyttsx3 was loaded correctly.

[pyttsx3 fails to execute when compiled](https://github.com/nateshmbhat/pyttsx3/issues/6)

[fixed / workaround for pyttsx3 test won't work once compiled with pyinstaller](https://github.com/pyinstaller/pyinstaller/issues/3268)

**Comment by nateshmbhat** [comment]
Issue is related to pyinstaller
