### ISSUE TITLE
OSError: libespeak.so.1: cannot open shared object file: on AWS linux

### ISSUE THREAD

**Issue by Shivampurbia** [nateshmbhat/pyttsx3#175]
I am not able to install Libespeake and espeak on AWS ec2.
it says "No package libespeak1 available." and "No package espeak available."
help please.

**Comment by TotallyAProgrammer** [comment]
`libespeak` is an outdated and often unsupported package. Please use eSpeak-NG.

**Comment by willwade** [comment]
espeak - for anyone asking - you do need to install espeak-ng 
It should really be some kind of dependency in the setup scripts - anyway..

Follow this guide: https://github.com/espeak-ng/espeak-ng/blob/master/docs/guide.md#installation

I might be going mad but eSpeak was pretty broken - I think I have fixed most issues including finding the dll in this fork/PR

https://github.com/thevickypedia/py3-tts/pull/6
