### ISSUE TITLE
Teaching

### ISSUE THREAD

**Issue by Kanfit** [nateshmbhat/pyttsx3#176]
How to teach pyttsx3? Working on software assistant and as a key word I want to use "Catia"
So, using pyttsx3 I get really weird pronunciation.
Should be like below:
[https://forvo.com/word/catia/](url)

**Comment by TotallyAProgrammer** [comment]
There is no way to "teach" pyttsx3 to speak a word a certain way. pyttsx3 is just a wrapper for various TTS engines. In order to "teach" the TTS engine, you would have to modify the speech model the TTS engine uses.

**Comment by Kanfit** [comment]
Thanks. Got that
