### ISSUE TITLE
save_to_file() inconsistent depending on text length, punctuation

### ISSUE THREAD

**Issue by jaredkeil** [nateshmbhat/pyttsx3#177]
On MacOS Catalina, in conda environment. I have been getting inconsistent results from `engine.save_to_file(text, filename)`.

Sometimes, it saves a reading of the whole text. Sometimes it cuts off randomly. Almost always it will stop on certain punctuation (Periods seem to always stop it. Commas usually get through, sometimes not.)

I am somewhat of the belief that this is a 'nsss' driver issue, and maybe something with communication about the queue between pyttsx3 and nsss.

```python
engine = pyttsx3.init()

text = "A short phrase. Another little bit"

save_dir = 'audio/'
t = str(time.strftime("%H%M%S", time.localtime()))
fname = t + '.aiff'

engine.save_to_file(text, save_dir + fname)
engine.runAndWait()
```

The resulting file, on playback, only says "A short phrase"

Here's another example... Everything the same, just changing the text variable :

```python
text = "A short phrase but longer"
```
This works.

Other punctuation not working, colons and commas(sometimes)
```python
text = "A short phrase: with a colon"
```
Playback: "A short phrase"

```python
text = "A short phrase, with a comma"
```
Playback: "A short phrase"

But for some reason, if I put the comma farther into the string, it reads it fine?
 
```python
text = "I'm gonna talk a little bit longer before adding a comma, but I will. "
```
Playback: "I'm gonna talk a little bit longer before adding a comma, but I will. "

Another issue: length of the text seems to change how much audio is saved. But it cuts off if the 'text' var is too long. I tried testing this with simply 'multiplying' the string.

```python
text = 10 * "A short phrase to repeat " 
```
^ No problem, outputs a file where the phrase is repeated 10 times.
File size: 513 KB
Duration: 12 sec

But this doesn't work as expected:
```python
text = 100 * "A short phrase to repeat " 
```
In audio, phrase only repeats 15 times, then stops in the middle of a new phrase, as it starts to say, "A".
I tried running it a few times, and it always ends up with the exact same number of repeats, and file size.
File size: 773 KB
Duration: 17 sec

Now, it gets interesting:
```python
text = 50 * "A short phrase to repeat " 
```
File size: 2.6 MB
Duration: 58 sec

I actually listened to the whole thing, it repeats it 50 times.

I tried doing 40 repeats, it is correct. With 60 repeats, however, it breaks off, and the file is actually smaller than the attempt with 50 repeats.

Sorry for this long post, just wanted to explain as much as I could about how it's acting.

**Comment by TotallyAProgrammer** [comment]
Im sorry for the late reply, been busy with life and stuff. I've tested this issue on Windows with SAPI5, and it doesn't have the issue you are having. I'm going to test it on a Linux machine in a minute with eSpeak-ng. It sounds like it is an NSSS or NSSS's driver.

**Comment by TotallyAProgrammer** [comment]
After some testing with Linux, it doesn't look like this is an issue on here either. I'd recommend installing eSpeak-ng (with homebrew or something of the likes), and telling pyttsx3 to use that.
`tts = engine.init(engine="espeak")`

**Comment by stnbu** [comment]
I have problems similar to this poster (I am using Big Sur). I found an old post with a Mac user having the same problem: https://developer.apple.com/forums/thread/106861

Maybe there is a different API call if you _don't_ want it to stop at the "end of the first sentence" (which seems like the behavior...maybe)

The [docs](https://developer.apple.com/documentation/appkit/nsspeechsynthesizer) suggest that you can either have "word boundaries" or "sentence boundaries" and synthesis stops either way at the boundary. Those two are your only choices.

I've experimented with `isSpeaking` and `continueSpeaking()` but without any real success.

**Comment by stnbu** [comment]
Any Mac uses who want local TTS and don't mind a _crude hack_ ...

```py
def osx_alex_say_subproc(input):
    import subprocess
    path = get_audio_cache_path(input, "alex", "aiff")
    command = ["say", "-v", "Alex", input, "-o", path]
    logging.info("Running: Popen(%s)" % (command))
    proc = subprocess.Popen(command)
    proc.wait(timeout=2)
    logging.info("Popen(%s) exitied with status %d" % (command, proc.returncode))
    return path
```

That works for me. Gross, but it works.

**Comment by willwade** [comment]
I’m pretty confident this is actually fixed on latest releases. I’ll double check this in a couple of weeks

**Comment by nateshmbhat** [comment]
> I’m pretty confident this is actually fixed on latest releases. I’ll double check this in a couple of weeks 

Thanks
