### ISSUE TITLE
isBusy() is always True

### ISSUE THREAD

**Issue by UnexpectedMaker** [nateshmbhat/pyttsx3#179]
Hi - what an amazing library thanks!!!

I'm wanting to see if the system is speaking or not, so I can block listening, and I thought I could use `engine.isBusy()` but that reports True regardless of if anything is being said or not.

Is that a bug? or is there an alternate way I can detect of the library is speaking or not?

**Comment by TotallyAProgrammer** [comment]
This sounds like a bug to me. What system are you experiencing this issue on?

**Comment by UnexpectedMaker** [comment]
> This sounds like a bug to me. What system are you experiencing this issue on?

Raspberry PI (Latest Raspberry pi os) running Python 3.7.3 and macOS (Catalina) running python 3.8.5

**Comment by TotallyAProgrammer** [comment]
Yeah, this is most likely a bug. In the code for eSpeak it appears that there is nothing resetting the isBusy variable back to false, and as for NSSS, it seems like the isBusy should work fine.

**Comment by UnexpectedMaker** [comment]
Ok, I'll go over the NSSS driver and match what they do in the eSpeak driver and see if I can get it working.

**Comment by willwade** [comment]
ok - hard to fully test this without example code but im pretty sure this is squashed. feel free to reopen if you see it again
