### ISSUE TITLE
implement SAPI's Pause and "Resume" for controling delay between words.

### ISSUE THREAD

**Issue by shula** [nateshmbhat/pyttsx3#18]
I'd like to control the delay between words.

It seems that the methods to use are:  Pause( ) and Resume() , implemented by SAPI 5.4

I don't know if these are exposed to pyttsx3, and if they are - how to add them to the onWord event, since it's defined and invoked from another class.

(see complete question + examples:  https://stackoverflow.com/questions/49840895/how-to-increase-delay-between-words-in-sapi-text-to-speech )

thanks!

**Comment by Kerang** [comment]
Simplest way to do that would be to speak the words in separate commands and use your code to control the time to wait between each command. The stackoverflow you've referenced is no longer available.

I assume this is what you're referring to: [how to lengthen the pause between the words with text-to-speech](https://stackoverflow.com/questions/4172541/how-to-lengthen-the-pause-between-the-words-with-text-to-speech-pytts-or-sapi5)

**Comment by willwade** [comment]
This is actually pretty fiddly with the way this library is designed. Nice idea though. I’ll have a think
