### ISSUE TITLE
Text-To-Speech Playback does not stop on KeyboardInterrupt

### ISSUE THREAD

**Issue by TheLegendBeacon** [nateshmbhat/pyttsx3#184]
The title says it all.

On playback of the sound, KeyboardInterrupt has no effect. 

Steps to replicate:
1) Type something long to TTS.
2) Try initiating the KeyboardInterrupt.

It only stops playing once it is done with the text.

**Comment by nateshmbhat** [comment]
Can someone raise a PR for this please 🙏🏻

**Comment by DGrothe-PhD** [comment]
I have checked out will wade's PR on thevickypedia's fork, on Windows, so this issue should be fixed as soon as will wade's PR is merged as it is. 

(I cannot say exactly which commit (in four years history) did it)
