### ISSUE TITLE
runAndWait() causes opencv camera feed to freeze

### ISSUE THREAD

**Issue by corlangerak** [nateshmbhat/pyttsx3#188]
HI does anyone know why using pyttsx3 causes my opencv camera window to either close, or freeze?
I would like to be able to speak out detected objects. 
Any ideas to prevent this from happening or workaround?
Maybe I am missing something...

**Comment by FireHead90544** [comment]
Use Threading. You need to use pyttsx3 engine in separate thread instead of main thread. Let open-cv run on main thread and the pyttsx3 engine inside threading.Thread()
