### ISSUE TITLE
pyttsx3 not working due to libespeak.so.1 not found on heroku stack 20

### ISSUE THREAD

**Issue by mbegumgit** [nateshmbhat/pyttsx3#191]
I am unable to install i windows10? Is there anyother solution?
PS C:\Users\User\projects\Datascience\BeeWord_Project\Bee_Project> sudo apt install libespeak1
apt : The term 'apt' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:1 char:1

apt install libespeak1
  + CategoryInfo          : ObjectNotFound: (apt:String) [], CommandNotFoundException
  + FullyQualifiedErrorId : CommandNotFoundException

**Comment by mghorb** [comment]
Hi! Were you able to figure this out? Running into the same issue

**Comment by willwade** [comment]
Think this is largely fixed. I see quite a few heroku related issues but in essence I think they were espeak issues that should be - for the most part - fixed
