### ISSUE TITLE
no audio on deployment 

### ISSUE THREAD

**Issue by imvickykumar999** [nateshmbhat/pyttsx3#197]
audio is audible on localhost flask but not on herokuapp deplyment !!

https://imvickykumar999.herokuapp.com/news

![image](https://user-images.githubusercontent.com/50515418/120847134-b2c2b780-c590-11eb-90b4-03df73e1bf62.png)

**Comment by willwade** [comment]
I’m assuming you are deploying on a Linux instance. In which case make sure dependencies are installed and use save to file
