### ISSUE TITLE
Configure Github to indicate correct latest license

### ISSUE THREAD

**Issue by bluthen** [nateshmbhat/pyttsx3#200]
Currently github has the license for the repo as MPL. I think it has MPL because version 1.0 is under MPL.

Version 2.0->2.7 and was under MIT, but after 2.7 it was switch to GPL-3.0.

But the best thing to do is setup github to show the latest GPL-3.0 license for the project so people that want to do the right thing do not get confused.

**Comment by nateshmbhat** [comment]
the proper license is MPL which is suitable for library ( latest one ), will update this in the setup.py file also

**Comment by nateshmbhat** [comment]
Thanks for pointing it out :)
