### ISSUE TITLE
pyttsx3 doesn't output sound.

### ISSUE THREAD

**Issue by Karapatakis106** [nateshmbhat/pyttsx3#203]
Hello, I have written a code (220 lines) without errors and when I compile it, it doesn't output sound. The lines that causing the problem are: 
`    sel=input("What do you want, me to do? ")
    engine.say("What do you want, me to do?")
    engine.runAndWait`
**...**
`engine.say("Sorry, I didn't understand it or learnt it for now. ")
        engine.runAndWait
        print ("Sorry, I didn't understand it or learnt it for now. ")`

I have it installed and working. I have imported and initialized too.

**Comment by TMSConsulting** [comment]
@Karapatakis106, 
In the clip above, you don't have () at the end of the runAndWait command.  I duplicated your problem and that resolved it.  Hope this helps.

**Comment by Karapatakis106** [comment]
Fixed.
