### ISSUE TITLE
Could support for Indian Languages be added?

### ISSUE THREAD

**Issue by sairam4123** [nateshmbhat/pyttsx3#206]
Hi. I'm looking for an offline text to speech synth that can synthesize Indian Languages, could you please add Indian Language support any time soon?

**Comment by iroonman** [comment]
I also want to add hindi language support to this program .
and now this is not been able to hear a single hindi word we should do it .
there is a way to do this by using the google translate packages and use them there

**Comment by iamDyeus** [comment]
> Hi. I'm looking for an offline text to speech synth that can synthesize Indian Languages, could you please add Indian Language support any time soon?

instead of using English language, you could try Hinglish. That worked for me very well.

**Comment by sairam4123** [comment]
I'm looking for Tamil and Telugu. So yeah.On 05-Jan-2022 6:41 PM, Arsh ***@***.***> wrote:

Hi. I'm looking for an offline text to speech synth that can synthesize Indian Languages, could you please add Indian Language support any time soon?

instead of using English language, you could try Hinglish. That worked for me very well.

**Comment by willwade** [comment]
Look at https://github.com/willwade/tts-wrapper?tab=readme-ov-file and use Sherpa-onnx
