### ISSUE TITLE
how to change voice gender attribute with espeak

### ISSUE THREAD

**Issue by jacknlliu** [nateshmbhat/pyttsx3#21]
Is it possible to change the `pyttsx3.voice.Voice` `gender` attribute with espeak?

**Comment by userzhiyuan** [comment]
class Voice(object):
    def __init__(self, id, name=None, languages=[], gender=None, age=None):
        self.id = id
        self.name = name
        self.languages = languages
        self.gender = gender
        self.age = age

but is not Effective.

**Comment by Kerang** [comment]
That's not how you would use it.
If it was defined in getProperty and setProperty in the espeak engine file for pyttsx3, it could be used.
As far as I know the only way to change the gender is by changing the voice.

Try adding these lines:
```
voices = engine.getProperty('voices')
print(voices)
```
Assuming, it shows more than one voice, you should be able to change between them by referencing their position like this:
`engine.setProperty('voice', voices[1].id)`

**Comment by willwade** [comment]
Yep. As @josephalway says.  Closing this one.
