### ISSUE TITLE
Set default audio device

### ISSUE THREAD

**Issue by sdfdger** [nateshmbhat/pyttsx3#216]
Pyttsx3 defaults to my current default playback device setting, but I want Pyttsx3 to use a certain playback device different from my current default windows setting.

**Comment by willwade** [comment]
I've looked into this and it's quite frankly a complete rewrite of how we deal with audio. We could get espeak to do this on Linux with not much bother but macOS and windows it's more dependencies and more fiddly code. I'll note this though https://github.com/willwade/tts-wrapper?tab=readme-ov-file where I think it will be easier (ish) as we use sounddevice
