### ISSUE TITLE
save_to_file MP3 Header incompatible with ffmpeg

### ISSUE THREAD

**Issue by michaelqin3** [nateshmbhat/pyttsx3#217]
Tried using save_to_file as an mp3 then reading its length using mutagen and pydub which seem to both use ffmpeg. Both got a header not found error for the mp3 generated.

**Comment by coff33h** [comment]
the file save_to_file() generated is not mp3 format.
if you use `file` command in terminal, it tells the file is "IFF data, AIFF audio"

**Comment by willwade** [comment]
We need to improve the docs on this. It's a common issue.

**Comment by willwade** [comment]
I'm pondering on forcing the renaming of a file for saving to the right extension. May do this a PR. it's controversial..,
