### ISSUE TITLE
MacOS crash on runAndWait and endLoop

### ISSUE THREAD

**Issue by randdvorak** [nateshmbhat/pyttsx3#225]
Process quits after utterance because driver relies on PyObjC where NSApp terminate is called in endLoop.  There needs to be way to quit the stop the currentRunLoop without calling NSApp terminate.

**Comment by randdvorak** [comment]
see pull request 296 for fix

**Comment by karthik-xperi** [comment]
The fix was provided in [pull/226](https://github.com/nateshmbhat/pyttsx3/pull/226)
