### ISSUE TITLE
No module named 'win32com'

### ISSUE THREAD

**Issue by adhirmndl** [nateshmbhat/pyttsx3#23]
>  -> python pyttsx.py
> Traceback (most recent call last):
>   File "C:\python\lib\site-packages\pyttsx3\__init__.py", line 44, in init
>     eng = _activeEngines[driverName]
>   File "C:\python\lib\weakref.py", line 137, in __getitem__
>     o = self.data[key]()
> KeyError: None
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "pyttsx.py", line 7, in <module>
>     engine = pyttsx3.init();
>   File "C:\python\lib\site-packages\pyttsx3\__init__.py", line 46, in init
>     eng = Engine(driverName, debug)
>   File "C:\python\lib\site-packages\pyttsx3\engine.py", line 52, in __init__
>     self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
>   File "C:\python\lib\site-packages\pyttsx3\driver.py", line 75, in __init__
>     self._module = importlib.import_module(name)
>   File "C:\python\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "C:\python\lib\site-packages\pyttsx3\drivers\sapi5.py", line 3, in <module>
>     import win32com.client
> ModuleNotFoundError: No module named 'win32com'

**Comment by MrValdez** [comment]
try to install pywin32

$ pip install pywin32

**Comment by Kerang** [comment]
> If you recieve errors such as ``No module named win32com.client``, ``No module named win32``, or ``No module named win32api``, you will need to additionally install ``pypiwin32``.

**Comment by jainil3010** [comment]
> 
> 
> > If you recieve errors such as `No module named win32com.client`, `No module named win32`, or `No module named win32api`, you will need to additionally install `pypiwin32`.

Still Not Working It shows "No module named win32api"

**Comment by nateshmbhat** [comment]
Please use python 3, the support for python 2 is soon coming to end.

**Comment by Wlodarski** [comment]
I had the same exact problem and I am on Python 3.6. 

Both ``pip install pypiwin32`` and ``pip install pywin32`` executed but I still had the "No module named win32api" error.  Then I found this explanation :

THE PROBLEM :
> Win32 modules are not guaranteed to install correctly with pip.  

THE SOLUTION:
[Install them directly from packages provided by developers on github](https://github.com/mhammond/pywin32/releases)

You might want to include the direct link in the documentation. 

> If you receive errors such as ``No module named win32com.client``, ``No module named win32``, or ``No module named win32api``, you will need to additionally install pypiwin32 with the command ``pip install pypiwin32`` and/or [install the precompiled packages](https://github.com/mhammond/pywin32/releases) provided by developers on GitHub
 .

**Comment by shivam1423** [comment]
I have tried everthing now.
1) `pip install pywin32`
```
ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
ERROR: No matching distribution found for pywin32
```
2) `pip install pypiwin32`
```
Collecting pypiwin32
  Using cached pypiwin32-223-py3-none-any.whl (1.7 kB)
ERROR: Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32) (from versions: none)
ERROR: No matching distribution found for pywin32>=223 (from pypiwin32)
```
3) Even tried [installing the precompiled packages](https://github.com/mhammond/pywin32/releases) then copied the win32com folder inside my python3.6/site-packages/win32com. Still
`import win32com`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'win32com'
```
I am working on ubuntu os, can anyone help me with this.

**Comment by nateshmbhat** [comment]
Ubuntu doesn't need pypiwin32.

Please see the updated installation instructions in readme
