### ISSUE TITLE
License question about recorded utterances

### ISSUE THREAD

**Issue by AdamMiltonBarker** [nateshmbhat/pyttsx3#241]
Hi all, I have a question specific to licensing. I have used pyttsx3 to generate 5 classes of 1500 utterances that I am using in a project and plan to publish for download for the research community. As your software uses SAPI under the hood on Windows, what restrictions would I have with sharing the data generated by your software?

**Comment by willwade** [comment]
IANAL but I reckon you’ll be ok. It won’t have anything to do with this library but you’ll have to look at the Microsoft legal docs
