### ISSUE TITLE
[FR] add flite driver

### ISSUE THREAD

**Issue by eadmaster** [nateshmbhat/pyttsx3#246]
Add support for Flite, which sounds better than espeak in most cases, but supports fewer languages out of the box.

[source](https://rhasspy.readthedocs.io/en/latest/text-to-speech/)

EDIT: as alternative in the Ubuntu repos i've also found picotts in the `libttspico0` package, already requested [here](https://github.com/nateshmbhat/pyttsx3/issues/116).

**Comment by Jiangshan00001** [comment]
this is a good idea. 
i am trying to add the TTS package support to is package.
i may finish and put it here at the end of this month: https://github.com/Jiangshan00001/pyttsx4

**Comment by Akul2010** [comment]
Hi @Jiangshan00001 , would you like to work together? I am working on my own fork (https://github.com/Akul-AI/rlvoice-1)

I used your TTS package code (I can remove it if you don't agree) and I am working on support for Flite, RHVoice, and Mimic3.

**Comment by willwade** [comment]
PicoTTS is good but flite is worth considering too. The only problem is dependencies. This library is very very dependency light and I’m nervous of adding loads of engines to it. See https://github.com/willwade/tts-wrapper for something a bit different (although I’m pretty sure we’ve got to do some work on pico in that library)

going to close for now to clear up issues. Thanks for the suggestion.
