### ISSUE TITLE
OpenBSD Debugging

### ISSUE THREAD

**Issue by ArmanMirzaei** [nateshmbhat/pyttsx3#249]
Problem using it on OpenBSD: even though it successfully installs, There are errors. Can something be done for it please?

Possible solutions:
* Merely debugging and workaround modification
* Or revising the architecture to comply with the pure python design pattern so that the problem is automatically taken care of by the python maintainers, for the unknown new computing devices to exist in the future to come. that is done by removing all non pure pythonic dependencies including the backends that rely on things beyond the python standard library.

Even though installing new stuff on openbsd just for a script is incompatible with its philosophy, and that unnecessary external dependencies make a python program immobile, working is better than not working. just that the respected developers should note the importance of the concept of mobility.

thank you

**Comment by willwade** [comment]
I know this is a long time ago but if anyone out there can test the current release that would be good. I reckon you came across the many numerous espeak bugs which have been largely sorted
