### ISSUE TITLE
I do not get any error but no voice when I try to execute the codes

### ISSUE THREAD

**Issue by mandanovi** [nateshmbhat/pyttsx3#254]
I am using python 3.11, I also tried to use 3.10 but I get the same problem.
pip install pyttsx3

--- my code ---
import pyttsx3

engine = pyttsx3.init()
engine.say("I will speak this text")
engine.runAndWait()

**Comment by matthewsgj** [comment]
I had to install espeak before I got anything. I'm on Debian Linux so it was:
sudo apt install libespeak1

**Comment by Akul2010** [comment]
This is now out of support. I made a new version of this that is in support now. Please feel free to contribute by emailing me for write access and helping out.

**Comment by willwade** [comment]
Fixed a while ago
