### ISSUE TITLE
Add an option to save output to a temporary file

### ISSUE THREAD

**Issue by blacksmithop** [nateshmbhat/pyttsx3#261]
This creates a file named `hello.mp3`
```python
import pyttsx3

engine = pyttsx3.init()

engine.save_to_file('Hello World!', 'hello.mp3')
engine.runAndWait()
```
It would be great if it were possible to create a NamedTemporaryFile instead.

**Comment by Jiangshan00001** [comment]
i have done it in another way.
```
import pyttsx4

engine = pyttsx4.init()
b=BytesIO()
engine.save_to_file('Hello World!', b)
engine.runAndWait()
```

but it only works in windows sapi5 for now.
https://github.com/Jiangshan00001/pyttsx4
have a try if you need.

**Comment by blacksmithop** [comment]
@Jiangshan00001 Awesome! I had traced the calls to the sapi5 driver before but couldn't figure out how to save it.
