### ISSUE TITLE
engine.say

### ISSUE THREAD

**Issue by Ray94520** [nateshmbhat/pyttsx3#266]
Unfortunately I have another problem I cannot figure out
here is my code this is just testing

import pyttsx3
engine = pyttsx3.init()
engine.say('I will speak this text')
engine.runAndWait()

When I run this it always skips the first word you can't hear it
the only way it worked was to put a small word in front of the I followed by a ,
now when I run it is skips the first word and then announces the whole sentence after ,

What am I doing wrong how do I fix this
I tried doing the audio rate and when I slowed down to 50 I can hear everything
when I speeded up to 100 for normal voice it skips the first word or I can hear it

**Comment by Jiangshan00001** [comment]
which OS are you using?
what engine are you using?

**Comment by willwade** [comment]
Closing this one. I have a sneaky feeling this was seen in espeak but now fixed
