### ISSUE TITLE
How to solve the sound of "a"?

### ISSUE THREAD

**Issue by bli920370** [nateshmbhat/pyttsx3#275]
How to solve the sound of "a"?
Hi there.
When I use the sentence below, it always said "a" as "ei".
How could I handle it?
Thanks.
engine.say('What a lazy dog!', 'dog')

**Comment by Jiangshan00001** [comment]
try this one:
```
    engine = pyttsx4.init('coqui_ai_tts')
    engine.save_to_file('what a lazy dog.', 'what_a_lazy_dog.wav')
    engine.runAndWait()

```
the output is in the zip file below:

[what_a_lazy_dog.zip](https://github.com/nateshmbhat/pyttsx3/files/11583621/what_a_lazy_dog.zip)

**Comment by willwade** [comment]
I'm assuming this was espeak.
