### ISSUE TITLE
 NSSpeechDriver is overriding existing Objective-C class exception with pyttsx4

### ISSUE THREAD

**Issue by nouran-abdalazim** [nateshmbhat/pyttsx3#281]
I'm running the following simple code on Mac laptop M1 and python 3.8.8 using virtual environment

```python
import pyttsx4

engine = pyttsx4.init()
engine.say('How are you today?')
engine.runAndWait()
``` 

I receive the following error " NSSpeechDriver is overriding existing Objective-C class". I can not resolve this exception 

Thanks in advance

**Comment by Jiangshan00001** [comment]
run:pip freeze
and paste the output here.
it maybe the objc version and pyttsx4 version conflict.

**Comment by Jiangshan00001** [comment]
the easiest way to do is run:
pip install pyobjc==9.0.1
