### ISSUE TITLE
Is this a joke?

### ISSUE THREAD

**Issue by Marcophono2** [nateshmbhat/pyttsx3#282]
Sorry to ask but: Is this project a joke? The voice "quality" is somewhat from a C64 computer game from 1985! Or did I something wrong? After not bringing it to work on my Windows computer I tried it with Ubuntu with the default example code with that "crazy dog" with all available voices in a loop. Eeehm. No. thank you. :-)

**Comment by Jiangshan00001** [comment]
in linux, the default engine is espeak.
if you want better quality, you can try:

```
pip install pyttsx4
pip install TTS
```


`
engine = pyttsx4.init('coqui_ai_tts')

engine.say('this is an english text to voice test, listen it carefully and tell who i am.')
engine.runAndWait()
`
