### ISSUE TITLE
pypiwin32 is obsolete, use pywin32 instead

### ISSUE THREAD

**Issue by mrabarnett** [nateshmbhat/pyttsx3#284]
The instructions on PyPI say to install "pypiwin32", but that's obsolete and has been for a long time.

It should be saying to install "pywin32" instead.

**Comment by willwade** [comment]
I can't find this so I guess this has been completed. Please reopen if that's not the case. Thanks

**Comment by Avasam** [comment]
`pypiwin32` is still listed in the dependencies https://github.com/nateshmbhat/pyttsx3/blob/de65c3bd37047cc7366f4a5880f7ba5484e164f3/pyproject.toml#L46
