### ISSUE TITLE
Espeak error on Mac

### ISSUE THREAD

**Issue by steelliberty** [nateshmbhat/pyttsx3#285]
I am unable to get past this error. I do not know how to install a working espeak on a Macbook pro with Apple chip. 

OSError: dlopen(libespeak.so.1, 0x0006): tried: '/Users/steelliberty/miniconda3/envs/pythonspeech/lib/python3.10/lib-dynload/../../libespeak.so.1' (no such file)

I tried to install espeak-py but that failed to install.  ( metadata-generation-failed )

**Comment by willwade** [comment]
Im hoping this is now fixed.
