### ISSUE TITLE
``pyttsx3.drivers.nsss`` should use ``from objc import super``

### ISSUE THREAD

**Issue by ronaldoussoren** [nateshmbhat/pyttsx3#290]
A user on the python forum mentioned an error message related to ``super`` when using ``pyttx3``: https://discuss.python.org/t/attributeerror-super-object-has-no-attribute-init/33303

Looking at the code for the ``NSSpeech`` driver this is because the code uses the regular super instead of the PyObjC one. That often works, but can cause problems, see https://pyobjc.readthedocs.io/en/latest/core/super.html for more details.

To fix this add ``from objc import super`` to the imports in ``pyttx3.drivers.nsss``.

**Comment by miscCoder** [comment]
also found here https://stackoverflow.com/questions/76434535/attributeerror-super-object-has-no-attribute-init

**Comment by Akul2010** [comment]
I am adding fixes [here](https://github.com/Akul-AI/rlvoice-1/).

This project is dead now.
