### ISSUE TITLE
Add support for new natural voices by microsoft

### ISSUE THREAD

**Issue by Meshwa428** [nateshmbhat/pyttsx3#291]
It's been almost a year since Microsoft released 3 natural sounding voices for windows, namely Guy, Jenny and Aria. But still they are not supported by this library, it's my humble request please add those voices, because we beginner devs are tired of listening to that boring David.

**Comment by HeiligeKoe** [comment]
You can actually add the voices if you want to.

Go to the Registry Editor > HKEY_LOCAL_MACHINE > SOFTWARE > Microsoft > Speech_OneCore > Voices > Tokens. Here, export the voice that you want to use and edit the text file so that you replace all 'Speech_OneCore' to 'Speech', save it and open it with Registry Editor.

**Comment by Meshwa428** [comment]
Any updates??

**Comment by Meshwa428** [comment]
Any updates?

**Comment by gexgd0419** [comment]
Seems that Microsoft hasn't allowed third-party apps to use those natural voices yet.

The Narrator natural voices are offline ([embedded](https://learn.microsoft.com/azure/ai-services/speech-service/embedded-speech)) versions of [Azure AI Speech](https://learn.microsoft.com/azure/ai-services/speech-service/) voices. Microsoft limits third-party access to embedded speech models, and requires [submitting an application form](https://aka.ms/csgate-embedded-speech) if you want to use them.

However, if you want to have a try, here's my program called [NaturalVoiceSAPIAdapter](https://github.com/gexgd0419/NaturalVoiceSAPIAdapter). After installation, it can make Narrator natural voices accessible to all SAPI 5 compatible programs, including pyttsx3.

**Comment by Meshwa428** [comment]
Thanks 🙏, but will it work offline?

**Comment by gexgd0419** [comment]
It supports both online voices (from Microsoft Edge read aloud feature) and offline voices (installed Narrator natural voices on your system). You can choose what to use in the installer.

After installing the program, the new natural voices will appear in the voice list of pyttsx3. You can get the voice list with `engine.getProperty('voices')`, and set which voice to use with `engine.setProperty('voice', voice.id)`.

Note that this is not supported by Microsoft, and may stop working after some system update. You can try this yourself, but using this in production is not recommended.

**Comment by willwade** [comment]
This a freakin awesome hack. Many thanks @gexgd0419 ⭐️
