### ISSUE TITLE
Which languages do you support?

### ISSUE THREAD

**Issue by dejudicibus** [nateshmbhat/pyttsx3#293]
There is nowhere a list of the languages it supports. Which languages are supported? Is it possible to add new ones?

**Comment by willwade** [comment]
Just to be clear to anyone wondering this too - Its not straightforward to answer this for this python library. This is a library largely to make use of your system/inbuilt TTS (excluding espeak of course - that has endless languages. Probably the most any TTS engine supports). Take SAPI - it all depends on what language packs you have already installed. This may be of use to anyone out there https://ttsvoicesavailable.streamlit.app
