### ISSUE TITLE
How to remove pauses between completions

### ISSUE THREAD

**Issue by deezed420** [nateshmbhat/pyttsx3#294]
How do I remove the pauses after every completion? I am trying to make the engine say stuff from a ChatGPT streaming API but that pause between each completion removes the fluency and makes it basically unusable. I can't just join them into a sentence because the ChatGPT streaming API takes a while for big completions. Here is what I have tried:
```python
import pyttsx3
 
words = ['this,','is,','my,','list']
join_words = ' '.join(words)
engine = pyttsx3.init()
engine.say(join_words)
engine.runAndWait()
```

but this gives very jagged pauses between the words

**Comment by willwade** [comment]
remove your commas. SAPI/NSSS will always put a timing gap in with the commas. Just like you'd expect in natural speech. 

i.e.

```python
import pyttsx3
 
words = ['this','is','my','list']
join_words = ' '.join(words)
engine = pyttsx3.init()
engine.say(join_words)
engine.runAndWait()
```
