### ISSUE TITLE
Does not speak some languages

### ISSUE THREAD

**Issue by onyekaokonji** [nateshmbhat/pyttsx3#298]
I am trying to build an online translator and when I use the package, it works for some languages while not working for others. For example, it doesn't work for Indian languages and Korean languages. Works well for English, French, Russian etc.

I am using a MacOS setup, adding that in case there is something I need to do.

**Comment by Akul2010** [comment]
I don't think you can add voices, try using gTTS instead I guess?

**Comment by holytony** [comment]
> I am trying to build an online translator and when I use the package, it works for some languages while not working for others. For example, it doesn't work for Indian languages and Korean languages. Works well for English, French, Russian etc.
> 
> I am using a MacOS setup, adding that in case there is something I need to do.

you can go to System Setting-> Accessibility->Spoken Content->System Voice->Manage Voices to take a look at what voices you have installed and what else are  available

**Comment by willwade** [comment]
@onyekaokonji are you sending it the correct text? also, just to be clear, what OS/Engine are you using? There is a difference. You could try https://github.com/willwade/tts-wrapper - which I do have working with all sorts of texts (and you might like sherpa-onnx which supports around 1300 languages offline)

**Comment by willwade** [comment]
Going to close this as not really fixable
