### ISSUE TITLE
How i can save voice in a windows file. EX: wav or mp3

### ISSUE THREAD

**Issue by AjaxFB** [nateshmbhat/pyttsx3#30]
pyttsx3 have this feature or not?
If not, how you and i can help to development this feature?

Thanks

**Comment by Kerang** [comment]
The feature has been implemented for MacOS [https://github.com/nateshmbhat/pyttsx3/pull/19](https://github.com/nateshmbhat/pyttsx3/pull/19)

The person that added the patch, only had an Apple device, so didn't implement the feature Windows or Linux. Trying to use the feature from Windows or Linux will throw an exception (NotImplementedError).

**Comment by JohnTravolski** [comment]
I am also interested in this functionality for Windows.  Please let me know if and when it is possible.

**Comment by dantistus** [comment]
It is so sad that we cannot have this functionality on Windows :'(

**Comment by kyb3r** [comment]
Wating on #57

**Comment by nateshmbhat** [comment]
Merged #57
