### ISSUE TITLE
engine.say("^") is not working

### ISSUE THREAD

**Issue by shiva396** [nateshmbhat/pyttsx3#307]
"^" is not working with voice type 2

```python
import pyttsx3
engine = pyttsx3.init()
engine.setProperty('rate', 100)
voices = engine.getProperty('voices')
engine.setProperty('voice', voices[1].id)
print(voices[1].id)
engine.say("^")
engine.runAndWait()
``` 

Name of the file : 
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_EN-US_ZIRA_11.0`

**Comment by willwade** [comment]
Umm what were you expecting it say?

**Comment by shiva396** [comment]
Often called a “caret,” “hat,” “circumflex,” or “exponent.”...
May be the main use case could be considered. i.e., "exponent"

**Comment by willwade** [comment]
Ok. I think you would be best defining a dict to look up what these characters should say and send them to the engine. I'd be nervous of doing this in the engine if pyttsx3 though. Each engine does things differently- particularly espeak. Infact I wouldn't mind betting carat actually means something else dependent on the language of the voice. 

In short - if it says nothing it's probably for good reason.  The underlying speech engine either understands it and it isn't what you are expecting or it doesn't

**Comment by shiva396** [comment]
Agreed! A dict for dialogue is safer since TTS engines handle symbols differently. For example, if you pass "2^3," the engine might not interpret it as "2 to the power of 3," and the user would expect that. My POV;
