### ISSUE TITLE
getting error even after installing pypiwin32

### ISSUE THREAD

**Issue by MarkJaco** [nateshmbhat/pyttsx3#31]
So im still getting this error:

ModuleNotFoundError: No module named 'win32api'

but i have already installed pypiwin32, so what now?

**Comment by Kerang** [comment]
I posted a functional example here: #33
Does that work for you?

See here, if you're compiling the file with pyinstaller and trying to run the executable:
[https://github.com/pyinstaller/pyinstaller/issues/3268](https://github.com/pyinstaller/pyinstaller/issues/3268)
