### ISSUE TITLE
Can I change the volume max limit from 1.0 to 5.0?

### ISSUE THREAD

**Issue by VolmerAndrei** [nateshmbhat/pyttsx3#310]
I am trying to make a tkinter.Spinbox control the rate and another to control the volume. The rate was easy, but the volume has a limit. From what I can see volume can be from 0.0 to 1.0
Is there a way to change the max limit?

**Comment by willwade** [comment]
What engine/OS are you using? the short answer is - probably not, at least in the voice. But you can do some things on sounddevice or pyaudio pretty easily
