### ISSUE TITLE
The engine doesn't work in the thread until the script is completed

### ISSUE THREAD

**Issue by Strange-RRR** [nateshmbhat/pyttsx3#327]
The following little script demonstrates the issue:

`import pyttsx3, threading, time`
`def tts_loop():`
`    engine.startLoop()`
`engine = pyttsx3.init('sapi5')`
`tr = threading.Thread(target = tts_loop, name = "tts_loop")`
`tr.start()`
`for i in range(5):`
`    engine.say(i)`
`    time.sleep(2)`

The engine only says the first digit, then freezes until the end of the cycle and the script itself. After that, it says all the other digits.

**Comment by willwade** [comment]
The problem is startLoop is blocking

This works..

```python
import pyttsx3, time

engine = pyttsx3.init('sapi5')

for i in range(5):
    engine.say(i)
    engine.runAndWait()
    time.sleep(2)
```

**Comment by Strange-RRR** [comment]
In your script the engine runs in the current thread, so I cannot execute any code during the engine is speaking. I wanted to run the engine as a separate thread

**Comment by Strange-RRR** [comment]
I found a solution. The engine should be initiated and run in the same thread:

```python
import pyttsx3, threading, time

engine = None

def loop():
    global engine
    engine = pyttsx3.init('sapi5')
    engine.startLoop()

t = threading.Thread(target = loop, name = "tts_loop")
t.start()
while engine is None:
    time.sleep(0)

for i in range(5):
    engine.say(i)
    time.sleep(2)
```

**Comment by Strange-RRR** [comment]
The following script more clearly demonstrates the benefits of such use:
```python
import pyttsx3, threading, time

engine = None

def loop():
    global engine
    engine = pyttsx3.init('sapi5')
    engine.startLoop()

t = threading.Thread(target = loop, name = "tts_loop")
t.start()
while engine is None:
    time.sleep(0)

engine.setProperty("rate", 150)
engine.say("This is a TTS engine test.")
engine.say("""This text is intentionally made large to show the benefits \
of running the TTS engine as a separate thread. You can see a stopwatch \
counting the time during the engine is speaking. It means you can execute \
any code during the engine is speaking.""")

counter = 0
while engine.isBusy():
    print(counter, end = " ")
    counter += 1
    time.sleep(1)
print()
engine.endLoop()
```
