### ISSUE TITLE
Skipping over words on Linux

### ISSUE THREAD

**Issue by marcswn** [nateshmbhat/pyttsx3#334]
Hello, I am using pyttsx3 in a flask application hosted on PythonAnywhere, which runs Ubuntu. I've found that the generated audio skips over words. The behavior is different with different texts, and from my testing I have found it to be affected by punctuation (similar to this issue #177, though I am using Linux instead of macOS). However, words would be skipped even if there is no punctuation at all--in this case it's often the last few words that are skipped. And if I add on punctuation at the very end of the text, it tends to be those words at the very end that get spoken. None of this happens running on my local windows machine.

My code is as follows:

```python
def create_diction_file_simple(text, rate, voice):
    engine = pyttsx3.init()
    engine.setProperty('rate', rate)
    set_voice(engine, voice)
    temp_filename = "temp.wav"
    engine.save_to_file(text, os.path.join(os.getcwd(), temp_filename))
    engine.runAndWait()
    diction_file = AudioSegment.from_file(os.path.join(os.getcwd(), temp_filename)) # Using pydub
    return diction_file
```

The `temp_filename` that is saved already is already missing the words, so I think the error must be in the `save_to_file()` method, or else due to `runAndWait()` not waiting for the full duration or something (but this is less likely, considering often the end text is spoken). It could also be because of the _espeak_ engine, though, but I don't know how I can find out if that's the case. I am at a complete loss what to do. I am more than happy to provide further information from testing, and I would appreciate any help.

**Comment by catherine-rb** [comment]
Similar problems with the speech cutting off mid-sentence on linux. (kbuntu). Code is: 

`engine = pyttsx3.init()
engine.say("oh my goodness this is a long piece of text and I don't know what to do with it.")
engine.runAndWait()`

and the speech cuts off at "to do-". Varying the text, it seems to be losing the last three phenomes. This starred wtih the 2.97 update.

**Comment by willwade** [comment]
Yeah. I can confirm I’ve seen this. To confirm - t’s on espeak whether it’s windows macOS or Linux. I’ll be honest I was stumped by this.

**Comment by willwade** [comment]
And could hear anything?

**Comment by catherine-rb** [comment]
I've switched to playing with 2.98. I'm seeing the words in the test code (not sure why my colleague wasn't yesterday): 

```
starting None
word The 1 3
word quick 5 5
word brown 11 5
word fox 17 3
word jumped 21 6
word over 28 4
word the 33 3
word lazy 37 4
word dog 42 3
```
 
Interestingly, when I run the first example on the page (Speaking text - sally and the dog) only the second sentence is output (minus the final word). 

It also hangs when I try the second example (Saving voice to a file):
`sh: 1: ffmpeg: not found`
In older versions it simply failed (with the same error).

**Comment by willwade** [comment]
Ok. Thanks a million for this. The ffmpeg error intrigues me. I swear I got rid of needing that. Ok. I’ll dig into this next week hopefully.

**Comment by willwade** [comment]
can any of you do me a favour and test this?

pip install git+https://github.com/willwade/pyttsx3.git@master

then run your code.. Tested on macos - I really need some testing on windows and linux
