### ISSUE TITLE
How to destroy instance of pyttsx3 engine ?

### ISSUE THREAD

**Issue by akash1305** [nateshmbhat/pyttsx3#34]
```python
self.engine = pyttsx3.init()
speech_rate = self.engine.getProperty('rate')
speech_rate = speech_rate - 80
self.engine.setProperty('rate', speech_rate)
```

If I run the code above twice than the speech rate is decreased twice by 80 because the pyttsx3.init() is returning the already initialized engine as mentioned in docs.
I want to know how can I destroy this instance so that when I run this code again, the speech rate is decreased by 80 only once .

I am using spyder (python 3.6.5).

**Comment by Kerang** [comment]
`import pyttsx3

engine = pyttsx3.init()
speech_rate = engine.getProperty('rate')
speech_rate = speech_rate - 80
engine.setProperty('rate', speech_rate)

engine.say("test")
engine.runAndWait()`

Has the same speech rate as the following.

`import pyttsx3

engine = pyttsx3.init()
speech_rate = engine.getProperty('rate')
speech_rate = speech_rate - 80
engine.setProperty('rate', speech_rate)

engine = pyttsx3.init()
speech_rate = engine.getProperty('rate')
speech_rate = speech_rate - 80
engine.setProperty('rate', speech_rate)

engine.say("test")
engine.runAndWait()`

So, I'm not sure what you're doing that's causing it to reduce the speech rate twice.
Unless, you're not reinitializing `self.engine = pyttsx3.init()`.
