### ISSUE TITLE
Problems with some characters

### ISSUE THREAD

**Issue by ownchoice** [nateshmbhat/pyttsx3#4]
I'm using Python 3 in Windows 10 and I have problems with characters like "áéíóúñ".
The problem is in the line 50 of the file sapi.py
` self._tts.Speak(toUtf8(text), 19)`

It receives bytes, not text.
For example, this text:
> Ñandú.

Will be received like:
`b'\xc3\x91and\xc3\xba.'`

I solved that problem changing that line to:
`self._tts.Speak(fromUtf8(toUtf8(text)), 19)`

And of course, changing:
`from . import toUtf8`

To:
`from . import toUtf8, fromUtf8`

**Comment by nateshmbhat** [comment]
Thanks for your work . 👍
