### ISSUE TITLE
Universal flag missing?

### ISSUE THREAD

**Issue by jhermann** [nateshmbhat/pyttsx3#40]
You advertise working under py2/3, but I see no universal flag anywhere (and your released wheel is py3 only).

**Comment by Kerang** [comment]
[https://github.com/nateshmbhat/pyttsx3/blob/master/pyttsx3/drivers/__init__.py](https://github.com/nateshmbhat/pyttsx3/blob/master/pyttsx3/drivers/__init__.py)

Being compatible with Python 2, doesn't mean he's supporting the release for Python 2. In reality, you should be moving to Python 3, for anything that's not a legacy application.
