### ISSUE TITLE
pyttsx3 not working in ubuntu.

### ISSUE THREAD

**Issue by hacksrk** [nateshmbhat/pyttsx3#41]
when i run the sample pyttsx3 code .
```
import pyttsx3

engine = pyttsx3.init()
engine.say("hello")
engine.runAndWait()

```
i get the following error:

> Traceback (most recent call last):
>   File "/home/sivaramakrishnan/.local/lib/python3.6/site-packages/pyttsx3/__init__.py", line 44, in init
>     eng = _activeEngines[driverName]
>   File "/usr/lib/python3.6/weakref.py", line 137, in __getitem__
>     o = self.data[key]()
> KeyError: None
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "speaker.py", line 3, in <module>
>     engine = pyttsx3.init()
>   File "/home/sivaramakrishnan/.local/lib/python3.6/site-packages/pyttsx3/__init__.py", line 46, in init
>     eng = Engine(driverName, debug)
>   File "/home/sivaramakrishnan/.local/lib/python3.6/site-packages/pyttsx3/engine.py", line 52, in __init__
>     self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
>   File "/home/sivaramakrishnan/.local/lib/python3.6/site-packages/pyttsx3/driver.py", line 75, in __init__
>     self._module = importlib.import_module(name)
>   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/sivaramakrishnan/.local/lib/python3.6/site-packages/pyttsx3/drivers/espeak.py", line 5, in <module>
>     from . import _espeak, toUtf8, fromUtf8
>   File "/home/sivaramakrishnan/.local/lib/python3.6/site-packages/pyttsx3/drivers/_espeak.py", line 18, in <module>
>     dll = cdll.LoadLibrary('libespeak.so.1')
>   File "/usr/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
>     return self._dlltype(name)
>   File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: libespeak.so.1: cannot open shared object file: No such file or directory
>

**Comment by hacksrk** [comment]
I finally got the solution ,
just run ```sudo apt install libespeak1```
then the bug is fixed.
libspeak1 package is needed for running pyttsx3 in ubuntu.

**Comment by saria85** [comment]
I have tried the library in both Windows and Ubuntu.
In windows the sounds is good and natural but in ubuntu is crappy and like a robot.
Did you experience the same thing?

**Comment by Rajathbharadwaj** [comment]
> I have tried the library in both Windows and Ubuntu.
> In windows the sounds is good and natural but in ubuntu is crappy and like a robot.
> Did you experience the same thing?

Even I experienced the same thing. 
Any solutions you found?

**Comment by iamsrk** [comment]
install libespeak1 package in ubuntu.

**Comment by santhosh432** [comment]
sudo apt-get update && sudo apt-get install espeak

**Comment by kartikbisht2006** [comment]
Try this "sudo apt install libespeak1"

**Comment by Manuchehr3232** [comment]
```
rojects/My Jarvis Project/Jarvis.py"
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
aplay: main:830: ошибка открытия аудио-устройства: Устройство или ресурс занято
```
libespeak1 not work

**Comment by aryanxorian** [comment]
> I have tried the library in both Windows and Ubuntu.
> In windows the sounds is good and natural but in ubuntu is crappy and like a robot.
> Did you experience the same thing?

chutiya laptop hai tera

**Comment by akreddy051** [comment]
> > I have tried the library in both Windows and Ubuntu.
> > In windows the sounds is good and natural but in ubuntu is crappy and like a robot.
> > Did you experience the same thing?
> 
> chutiya laptop hai tera

sachme aisa aara hai bhai awaaz. laptop chutiya nhi .advice chutiya hai

**Comment by JWBWork** [comment]
I'm also having this problem, anyone found a solution to this?
https://github.com/nateshmbhat/pyttsx3/issues/151

**Comment by austin-tp** [comment]
sudo apt-get update && sudo apt-get install espeak

**Comment by Stealth1993** [comment]
I have this issue while running on Android.

**Comment by ashraf-minhaj** [comment]
This might be late but try this on linux - 
`
 pip3 install pyAudio
 sudo apt-get install libespeak1
 pip3 install Pyttsx3
 `

**Comment by Shivampurbia** [comment]
bro, I am facing the same problem.
it was working on windows but the same code is giving me the error mentioned above on was Linux I am not able to install speak as well as libspeak1 it says no package available.

bhai help krde yrrrrrr.

**Comment by JWBWork** [comment]
[So I found a solution to my problem](https://github.com/nateshmbhat/pyttsx3/issues/151). In my case when attempting to save to a file the run and wait function wasn't actually waiting on Linux. So I just ran a sleep function in a while loop where the loop's condition checks for the file, there's an example in the link.

**Comment by mbegumgit** [comment]
> sudo apt install libespeak1

I am unable to install i windows10? Is there anyother solution?
PS C:\Users\User\projects\Datascience\BeeWord_Project\Bee_Project> sudo apt install libespeak1
apt : The term 'apt' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was       
included, verify that the path is correct and try again.
At line:1 char:1
+ apt install libespeak1
+ ~~~
    + CategoryInfo          : ObjectNotFound: (apt:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by rohitsharma139** [comment]
t

> > sudo apt install libespeak1
> 
> I am unable to install i windows10? Is there anyother solution?
> PS C:\Users\User\projects\Datascience\BeeWord_Project\Bee_Project> sudo apt install libespeak1
> apt : The term 'apt' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
> included, verify that the path is correct and try again.
> At line:1 char:1
> 
> * apt install libespeak1
> * ```
>     + CategoryInfo          : ObjectNotFound: (apt:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
>   ```

this works on linux only!!

**Comment by cocsiam435** [comment]
Debian
    apt-get install alsa-utils 
Ubuntu
    apt-get install alsa-utils 
Alpine
    apk add alsa-utils 
Arch Linux
    pacman -S alsa-utils 










Kali Linux
    apt-get install alsa-utils 
CentOS
    yum install alsa-utils 
Fedora
    dnf install alsa-utils 
Raspbian
    apt-get install alsa-utils 
Docker
    docker run cmd.cat/aplay aplay

**Comment by aakash-shakya** [comment]
had a issue  `sh: 1: aplay: not found` in kali linux. 
But issue is resolved after  installing alsa-utils using command `apt-get install alsa-utils`.

Hope it might help.

Look at commands as per your distro on @cocsiam435  's thread.

**Comment by jopvivi** [comment]
> I finally got the solution , just run `sudo apt install libespeak1` then the bug is fixed. libspeak1 package is needed for running pyttsx3 in ubuntu.

I got my code here to run to completion, without errors: https://github.com/jopvivi/pdf_to_speech/blob/master/clean/speak.py

But unfortunately it fails to create the wave files like it does in windows.

**Comment by 0ne-zero** [comment]
> At first type sudo apt-get update && sudo apt-get install espeak (this commands works on debian based distros)
> 
> Then type the commands bellow according to your distro . I solved my problem this way.
> 
> Debian apt-get install alsa-utils Ubuntu apt-get install alsa-utils Alpine apk add alsa-utils Arch Linux pacman -S alsa-utils
> 
> Kali Linux apt-get install alsa-utils CentOS yum install alsa-utils Fedora dnf install alsa-utils Raspbian apt-get install alsa-utils Docker docker run cmd.cat/aplay aplay

I was keep getting "/tmp/tmp5_jvftmu: No such file or directory" error (not exception) in runAndWait() method (on fedora).
But It's helped me

**Comment by shivajigit** [comment]
> > I have tried the library in both Windows and Ubuntu.
> > In windows the sounds is good and natural but in ubuntu is crappy and like a robot.
> > Did you experience the same thing?
> 

aplay not installed
> try : sudo apt-get install alsa-utils

**Comment by Sokkernr1** [comment]
Running into a similar problem like @un-lock-me. I'm running pyttsx3 in a docker container and the created files sound awful. I created [this stackoverflow post ](https://stackoverflow.com/questions/73873102/running-pyttsx3-espeak-text-to-speech-in-docker-container-creates-awful-sound) for it. Maybe someone here can help?
