### ISSUE TITLE
Supress warnings

### ISSUE THREAD

**Issue by mlpcorreia** [nateshmbhat/pyttsx3#45]
Hi, I'm getting this on raspberry pi 3 b+, 
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front.
It works fine, but I would like to know if there is a way to supress this?

Thx for time

**Comment by Kerang** [comment]
> It you get the following error message:
> 
>     ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
> 
> Edit the file /usr/share/alsa/alsa.conf:
> 
>     sudo nano /usr/share/alsa/alsa.conf
>     change the line “pcm.front cards.pcm.front” to “pcm.front cards.pcm.default”
[http://cagewebdev.com/raspberry-pi-getting-audio-working/](http://cagewebdev.com/raspberry-pi-getting-audio-working/)

I've not tested the above solution. User discretion is advised.

**Comment by Kerang** [comment]
> Problem (1) Alsa.conf
> All of the warning messages can be fixed by making a change to the Alsa configuration.
> This will resolve all of the warning messages of the type:
> 
> Code: Select all
> 
> ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.<blah blah>
> 
> To change the Alsa configuration, issue the following command:
> 
> Code: Select all
> 
> pi@rpib2-1:/ $ sudo nano /usr/share/alsa/alsa.conf
> 
> Scroll down the file until you see text for the pcm defintion. For each pcm replace the text at the end of the definition with default. I will illustrate:
> 
> Original:
> 
> Code: Select all
> 
> pcm.front cards.pcm.front
> 
> Updated:
> 
> Code: Select all
> 
> pcm.front cards.pcm.default
> 
> I did this for each of the warning messages, about 15 in all. Save your file.
[https://www.raspberrypi.org/forums/viewtopic.php?p=913285](https://www.raspberrypi.org/forums/viewtopic.php?p=913285)

Apparently, it's complaining that there's no front speaker/port or something. Changing it to default fixes it, I guess.

**Comment by mlpcorreia** [comment]
That solved it. Thx!
