### ISSUE TITLE
libespeak.so.1

### ISSUE THREAD

**Issue by plathara** [nateshmbhat/pyttsx3#48]
OSError: libespeak.so.1: cannot open shared object file: No such file or directory

**Comment by zagm** [comment]
Hello,
the project depends on espeak.

Try installing system package with the following command:

apt-get update && apt-get install espeak # (or something similar if you are not using Debian based distro)

**Comment by nateshmbhat** [comment]
Refer this comment for the fix : 

https://github.com/nateshmbhat/pyttsx3/issues/38#issuecomment-599006878

**Comment by xuiqzy** [comment]
Should it work with espeak-ng, too?

**Comment by akshaykumar46** [comment]
no....i have tried...it is still not working

**Comment by akshaykumar46** [comment]
it works. thanks you all
