### ISSUE TITLE
Different voice

### ISSUE THREAD

**Issue by chaooe** [nateshmbhat/pyttsx3#50]
Do it support with different voice? It only have male and female. 

- [ ]

**Comment by Kerang** [comment]
I assume, it should work fine with a different voice, if you have a different voice installed. Otherwise, it will use the default.

Please see the section title "Changing Voice , Rate and Volume :" here: [https://github.com/nateshmbhat/pyttsx3](https://github.com/nateshmbhat/pyttsx3
)
