### ISSUE TITLE
pxttsx3 don^t work on mac os 10.13.6

### ISSUE THREAD

**Issue by Battant** [nateshmbhat/pyttsx3#54]
Hello,

Here is my configuration :
mac os 10.13.6
python3.7.3 install threow hambrow
brew install python

requirements file 

cat requarements_macos.txt 
Foundation
AppKit
PyObjC
#..voice

python3 speak.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyttsx3/__init__.py", line 44, in init
    eng = _activeEngines[driverName]
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "codereader.py", line 365, in <module>
    window = codeReaderWindow(root)
  File "codereader.py", line 198, in __init__
    self.make_widgets()
  File "codereader.py", line 233, in make_widgets
    self.engine = pyttsx3.init()
  File "/usr/local/lib/python3.7/site-packages/pyttsx3/__init__.py", line 46, in init
    eng = Engine(driverName, debug)
  File "/usr/local/lib/python3.7/site-packages/pyttsx3/engine.py", line 52, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/usr/local/lib/python3.7/site-packages/pyttsx3/driver.py", line 75, in __init__
    self._module = importlib.import_module(name)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/pyttsx3/drivers/nsss.py", line 2, in <module>
    from Foundation import *
ModuleNotFoundError: No module named 'Foundation'

pip3 install -r requarements_macos.txt 
Requirement already satisfied: Foundation in /usr/local/lib/python3.7/site-packages (from -r requarements_macos.txt (line 1)) (0.1.0a0.dev1)
Collecting AppKit (from -r requarements_macos.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/8b/93/5d77e3cccb45a065e9853869af66cf9b09353f51c629cfe040d094620866/AppKit-0.2.8.tar.gz
Requirement already satisfied: PyObjC in /usr/local/lib/python3.7/site-packages (from -r requarements_macos.txt (line 3)) (5.2)
Requirement already satisfied: Django<1.11,>=1.10 in /usr/local/lib/python3.7/site-packages (from Foundation->-r requarements_macos.txt (line 1)) (1.10.8)
Requirement already satisfied: django-sekizai>=0.10 in /usr/local/lib/python3.7/site-packages (from Foundation->-r requarements_macos.txt (line 1)) (1.0.0)
Collecting flask (from AppKit->-r requarements_macos.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/9a/74/670ae9737d14114753b8c8fdf2e8bd212a05d3b361ab15b44937dfd40985/Flask-1.0.3-py2.py3-none-any.whl
Collecting pygobject (from AppKit->-r requarements_macos.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/c1/36/c31a6ce9411b22a8ac0759c9b5ffda09368d5e0643450bb8ed83c271588c/PyGObject-3.32.1.tar.gz
  Installing build dependencies ... error
  Complete output from command /usr/local/opt/python/bin/python3.7 /usr/local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/xr/yqdmx4ld7ysgtqgbrzls8bdw0000gn/T/pip-build-env-zg4bltih/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel pycairo:
  Collecting setuptools
    Using cached https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl
  Collecting wheel
    Using cached https://files.pythonhosted.org/packages/bb/10/44230dd6bf3563b8f227dbf344c908d412ad2ff48066476672f3a72e174e/wheel-0.33.4-py2.py3-none-any.whl
  Collecting pycairo
    Using cached https://files.pythonhosted.org/packages/48/20/5e83af98eb897935bf7dc39455e892ba866feebb9b7c3b392982866f9958/pycairo-1.18.1.tar.gz
  Building wheels for collected packages: pycairo
    Building wheel for pycairo (setup.py): started
    Building wheel for pycairo (setup.py): finished with status 'error'
    Complete output from command /usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/xr/yqdmx4ld7ysgtqgbrzls8bdw0000gn/T/pip-install-pt6yln8u/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/xr/yqdmx4ld7ysgtqgbrzls8bdw0000gn/T/pip-wheel-517nrm5g --python-tag cp37:
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.13-x86_64-3.7
    creating build/lib.macosx-10.13-x86_64-3.7/cairo
    copying cairo/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/cairo
    copying cairo/__init__.pyi -> build/lib.macosx-10.13-x86_64-3.7/cairo
    copying cairo/py.typed -> build/lib.macosx-10.13-x86_64-3.7/cairo
    running build_ext
    Package cairo was not found in the pkg-config search path.
    Perhaps you should add the directory containing `cairo.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'cairo' found
    Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']' returned non-zero exit status 1.
  
    ----------------------------------------
    Failed building wheel for pycairo
    Running setup.py clean for pycairo
  Failed to build pycairo
  Installing collected packages: setuptools, wheel, pycairo
    Running setup.py install for pycairo: started
      Running setup.py install for pycairo: finished with status 'error'
      Complete output from command /usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/xr/yqdmx4ld7ysgtqgbrzls8bdw0000gn/T/pip-install-pt6yln8u/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/xr/yqdmx4ld7ysgtqgbrzls8bdw0000gn/T/pip-record-ox8g_200/install-record.txt --single-version-externally-managed --prefix /private/var/folders/xr/yqdmx4ld7ysgtqgbrzls8bdw0000gn/T/pip-build-env-zg4bltih/overlay --compile:
      running install
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.13-x86_64-3.7
      creating build/lib.macosx-10.13-x86_64-3.7/cairo
      copying cairo/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/cairo
      copying cairo/__init__.pyi -> build/lib.macosx-10.13-x86_64-3.7/cairo
      copying cairo/py.typed -> build/lib.macosx-10.13-x86_64-3.7/cairo
      running build_ext
      Package cairo was not found in the pkg-config search path.
      Perhaps you should add the directory containing `cairo.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'cairo' found
      Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']' returned non-zero exit status 1.
  
      ----------------------------------------
  Command "/usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/xr/yqdmx4ld7ysgtqgbrzls8bdw0000gn/T/pip-install-pt6yln8u/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/xr/yqdmx4ld7ysgtqgbrzls8bdw0000gn/T/pip-record-ox8g_200/install-record.txt --single-version-externally-managed --prefix /private/var/folders/xr/yqdmx4ld7ysgtqgbrzls8bdw0000gn/T/pip-build-env-zg4bltih/overlay --compile" failed with error code 1 in /private/var/folders/xr/yqdmx4ld7ysgtqgbrzls8bdw0000gn/T/pip-install-pt6yln8u/pycairo/
  
  ----------------------------------------
Command "/usr/local/opt/python/bin/python3.7 /usr/local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/xr/yqdmx4ld7ysgtqgbrzls8bdw0000gn/T/pip-build-env-zg4bltih/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel pycairo" failed with error code 1 in None

could you help me please to fix this issus ?

Best regards

Battant

**Comment by nateshmbhat** [comment]
The current build (pyttsx3 v2.84) should work fine now.
