### ISSUE TITLE
How can I add my own voice in Text to Speech?

### ISSUE THREAD

**Issue by harirawat** [nateshmbhat/pyttsx3#56]
I am creating an application which will read text in the user's voice. I am using pyttsx for text to speech conversion.

I want to know if there is any way by which the voice of the speech can be changed to the user's voice.

**Comment by ggeop** [comment]
> 
> 
> I am creating an application which will read text in the user's voice. I am using pyttsx for text to speech conversion.
> 
> I want to know if there is any way by which the voice of the speech can be changed to the user's voice.

You have to install different voices in your system. Your question is very close to a former issue (https://github.com/nateshmbhat/pyttsx3/issues/50)

**Comment by Kerang** [comment]
You'd have to create their voice as a voice and have that installed. I don't know how that would be possible.
