### ISSUE TITLE
pyttsx3 doesn't pronounce Indian Rupee Symbol ₹ 

### ISSUE THREAD

**Issue by akashgudadhe1** [nateshmbhat/pyttsx3#60]
I am using pyttsx3 in my project.I have to pronounce various currencies in which $ and other currencies are speaking properly but pyttsx3 doesn't pronounce Indian Rupee Symbol ₹. 

This is my python3 code :-
```
    import pyttsx3
    engine = pyttsx3.init()
    engine.say('₹')
    engine.runAndWait()
```

**Comment by Kerang** [comment]
Is the Indian Rupee symbol pronounced correctly using whichever TTS engine natively?

For example, if you're using espeak on linux, does it work on linux?
`espeak "₹"`

The question I have is this, is it really a "pyttsx3" problem? Or, is it a problem with the underlying system that pyttsx3 utilizes.

**Comment by nateshmbhat** [comment]
Its not an issue of pyttsx3.
