### ISSUE TITLE
How can I make pyttsx3 use installed mbrola voices?

### ISSUE THREAD

**Issue by solarjoe** [nateshmbhat/pyttsx3#66]
I would like to use the mbrola voices in pyttsx3, but failed so far.

When I run 
`espeak -v mb-de7 "Bitte etwas nach links!"`
on the command line it works fine, though the verbose output says

```
mbrola: mbrola: No such file or directory
mbrowrap error: mbrola exited with status 1
mbrola voice not found
```
in the beginning. But the voice seems correct (female German).

But when I iterate over the voices using 

`for voice in voices:`

there are only male voices and also nothing like `de7`, just some default set.
It does not show mbrola voices with prefix `mb`.

I downloaded the voices [here](https://github.com/numediart/MBROLA-voices) and copied them to several locations
e.g.
- `/usr/lib/arm-linux-gnueabihf/espeak-data/mbrola/de7/`
- `/usr/lib/arm-linux-gnueabihf/espeak-data/mbrola/`
- `/usr/share/mbrola`
- `/usr/share/mbrola/de7/`

but nothing worked. They did not show up in pyttsx3.

I have the folder `/usr/lib/arm-linux-gnueabihf/espeak-data/mbrola_ph` with files like 
`de6_phtrans` or `de4_phtrans` but nothing with `de7`. Also the files in there do not show up.

Version and directory info:

```
espeak --version
eSpeak text-to-speech: 1.48.03  04.Mar.14  Data at: /usr/lib/arm-linux-gnueabihf/espeak-data
```

Any ideas how this can be fixed?

**Comment by solarjoe** [comment]
When I run `espeak --voices` there is also nothing like `de7`.
This is just a part of the list:

```
 5  de             M  german               de            
 5  el             M  greek                europe/el     
 5  en             M  default              default       
 2  en-gb          M  english              en            (en-uk 2)(en 2)
 5  en-sc          M  en-scottish          other/en-sc   (en 4)
 5  en-uk-north    M  english-north        other/en-n    (en-uk 3)(en 5)
 5  en-uk-rp       M  english_rp           other/en-rp   (en-uk 4)(en 5)
 5  en-uk-wmids    M  english_wmids        other/en-wm   (en-uk 9)(en 9)
 2  en-us          M  english-us           en-us         (en-r 5)(en 3)
 5  en-wi          M  en-westindies        other/en-wi   (en-uk 4)(en 10)

```

**Comment by Kerang** [comment]
I've not messed with pyttsx3 on Linux and don't really have any experience with espeak. It seems to be quite telling, that the program pyttsx3 relies on to provide the list of voices, isn't listing the voice(s) you want. I would look into errors with espeak not properly listing / finding the voice(s) you have installed. As, it seems that espeak isn't recognizing them for whatever reason.

**Comment by Kerang** [comment]
A quick google search for "mbrola: mbrola: no such file or directory" brought me here: [http://espeak.sourceforge.net/mbrola.html](http://espeak.sourceforge.net/mbrola.html)

**Comment by nateshmbhat** [comment]
This issue seems to be related to espeak. 
Closing this for now.

Reopen if you get more updates on this issue...
