### ISSUE TITLE
engine.setProperty('voice', Voice[1].id) isn't working!

### ISSUE THREAD

**Issue by iamknownstranger** [nateshmbhat/pyttsx3#69]
`Traceback (most recent call last):
  File "joy.py", line 10, in <module>
    engine.setProperty('voice', voices[1].id)
NameError: name 'voices' is not defined`

The module is default working on the Microsoft TTS engine

`engine.getProperty('voice')
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_EN-US_ZIRA_11.0`

**Comment by Kerang** [comment]
Do you have this line above it?
`voices = engine.getProperty('voices')`

What does the following show?
```
import pyttsx3
engine = pyttsx3.init() # object creation

"""VOICE"""
voices = engine.getProperty('voices')       #getting details of current voice
#engine.setProperty('voice', voices[0].id)  #changing index, changes voices. o for male
#engine.setProperty('voice', voices[1].id)   #changing index, changes voices. 1 for female
print(voices)
```
