### ISSUE TITLE
We recommend adding the ability to save voice as a file

### ISSUE THREAD

**Issue by pruidong** [nateshmbhat/pyttsx3#7]
Much of what is currently on the Internet is not available for saving voice as a file, hoping to implement a way to save voice directly into a file. Thank you.

**Comment by Kerang** [comment]
MacOS X nsss driver reference [capturing tts output in python](https://stackoverflow.com/questions/8171867/capturing-tts-output-in-python)
> Your question implies it's ok if this is a Mac OS X only solution? If so, then you can modify the Mac OS X driver in pyttsx (pyttsx/drivers/nsss.py) and give it the ability to call the startSpeakingString:toURL: method on the NSSpeechSynthesizer class:
> 
> http://developer.apple.com/library/mac/#documentation/Cocoa/Reference/ApplicationKit/Classes/NSSpeechSynthesizer_Class/Reference/Reference.html
> 
> This will save synthesized text to a file.

Another MacOS X nsss driver reference [recording synthesized text to speech](https://stackoverflow.com/questions/9900137/recording-synthesized-text-to-speech-to-a-file-in-python)
```
#!/usr/bin/env python

from  AppKit import NSSpeechSynthesizer
import sys
import Foundation


if len(sys.argv) < 2:
   text = raw_input('type text to speak> ')
else:
   text = sys.argv[1]

nssp = NSSpeechSynthesizer
ve = nssp.alloc().init()
ve.setRate_(100)
url = Foundation.NSURL.fileURLWithPath_('yourpath/test.aiff')
ve.startSpeakingString_toURL_(text,url)
```
Linux espeak driver reference [how to save sound produced from text](https://stackoverflow.com/questions/17646949/how-to-save-sound-produced-from-text-as-mp3-or-wave-in-python)
Windows espeak driver reference [how to save the output of pyttsx to wav file](https://stackoverflow.com/questions/39014468/how-to-save-the-output-of-pyttsx-to-wav-file)
> import subprocess
> 
> def textToWav(text,file_name):
>    subprocess.call(["espeak",text,"-w"+file_name+".wav"])
> 
> textToWav('hello world','hello')

Windows sapi5 driver reference [tts - project on github](https://github.com/DeepHorizons/tts)
```
    def _create_stream(self, filename):
        """Create a file stream handler"""
        stream = comtypes.client.CreateObject('Sapi.SpFileStream')
        stream.Open(filename, SpeechLib.SSFMCreateForWrite)
        return stream

    def create_recording(self, filename, message):
        """Make a recording of the given message to the file
        The file should be a .wav as the output is
        PCM 22050 Hz 16 bit, Little endianness, Signed"""
        stream = self._create_stream(filename)
        temp_stream = self.voice.AudioOutputStream
        self.voice.AudioOutputStream = stream
        self.say(message)
self.voice.AudioOutputStream = temp_stream
```

**Comment by nateshmbhat** [comment]
Save to file implemented in Mac in #19

**Comment by nateshmbhat** [comment]
For windows it's almost done in #57

**Comment by nateshmbhat** [comment]
Save to file now supported in both windows and Mac

**Comment by spetr0s** [comment]
I have not been able to get save_to_file to work on Win10. Please provide a complete, but minimal example.  I am a Python novice.  Apparently, many others are having the same problem. Downloaded pyttsx3 2019-Oct-18.
Thanks.
[pyttsx3_2file_fails.txt](https://github.com/nateshmbhat/pyttsx3/files/3758868/pyttsx3_2file_fails.txt)

**Comment by andreynovikov** [comment]
@spetr0s on Windows it is saved to wav:

```
engine.save_to_file(myText, "opf.wav")
```

**Comment by khushbu-mulani** [comment]
> @spetr0s on Windows it is saved to wav:
> 
> ```
> engine.save_to_file(myText, "opf.wav")
> ```

@andreynovikov Is this working for you on linux as well? 
According to [#76](https://github.com/nateshmbhat/pyttsx3/pull/76) it should work, but there seems to be an issue with this

**Comment by naazneen** [comment]
> @spetr0s on Windows it is saved to wav:
> 
> ```
> engine.save_to_file(myText, "opf.wav")
> ```

Where is the saved file. I don't find it in the working directory.

**Comment by TNTgamer71** [comment]
Not working on linux from my testing, at least on a Raspberry Pi Zero W

**Comment by AlexApps99** [comment]
@nateshmbhat @fourjr
As seen by the comments above, #76 does not work on the majority of Linux setups (including my own), so this issue needs to be reopened.

**Comment by TNTgamer71** [comment]
I have moved onto using gTTS, due to the lack of saving to file on Linux. This really needs to be implemented (correctly).

**Comment by fourjr** [comment]
I have tested this again on a fresh linux vm, ensure you have instealled:
- ffmpeg
- espeak

and save_to_file should work

**Comment by AlexApps99** [comment]
I have both ffmpeg and espeak

**Comment by fourjr** [comment]
Try saving it as an mp3

**Comment by AlexApps99** [comment]
If you use ffmpeg, why wouldn't it save to wav as well?

**Comment by AlexApps99** [comment]
@fourjr as I said earlier, saving as both wav and mp3 doesn't work, it fails silently without raising any exceptions or printing anything.

If you need me to send a stack trace for debugging purposes, let me know.

This needs fixing.

**Comment by fourjr** [comment]
You need to run `driver.runAndWait()` to actually execute the commands.

Try the following snippet
```python
import pyttsx3
driver = pyttsx3.init()
driver.save_to_file('Hello World', 'test.mp3')
driver.runAndWait()
```

**Comment by AlexApps99** [comment]
That worked.

Obviously the problem here is that no documentation or examples were provided, (save_to_file isn't even included in the auto-generated docs), so users (myself included) were not aware of how to use it.

I think this issue should be closed after proper documentation and examples are added so it's clear how to use this functionality

**Comment by fourjr** [comment]
I agree and apologise for the confusion, @nateshmbhat could you add it into the autogenerated documentation?

**Comment by nateshmbhat** [comment]
adding

**Comment by nateshmbhat** [comment]
Updated README
