### ISSUE TITLE
AttributeError: module 'pyttsx3' has no attribute 'speak'

### ISSUE THREAD

**Issue by filips123** [nateshmbhat/pyttsx3#74]
Single line usage does not work because of attribute error for `pyttsx3.speak`.

```py
>>> import pyttsx3
>>> pyttsx3.speak('Hello World')

Traceback (most recent call last):
  File "<pyshell#28>", line 1, in <module>
    pyttsx3.speak('Hello World')
AttributeError: module 'pyttsx3' has no attribute 'speak'
```

**Comment by filips123** [comment]
The problem is that `pyttsx3.speak` was added 2 months ago, but that change is still not published on PyPI.

@nateshmbhat Can you publish new release?

**Comment by nateshmbhat** [comment]
its published now 👍

**Comment by maa-gic** [comment]
I tried suggestions from every source and nothing worked. This is what I did to finally remove the error:

![Capture](https://user-images.githubusercontent.com/121801240/233812665-8d7e7a23-655a-4acb-a965-caeb6d61d79d.PNG)
