### ISSUE TITLE
How to use pyttsx in a python thread

### ISSUE THREAD

**Issue by SqrtPapere** [nateshmbhat/pyttsx3#8]
I am working with `pyttsx3` for text-to-speech. I realized that I can't use it within a thread (or I am doing something wrong). Do you know why?

Code Example:

    from threading import Thread
    import pyttsx3

    def myfunc():
      engine = pyttsx3.init()
      engine.say("ok")
      engine.runAndWait()

    t = Thread(target=myfunc)
    t.start()

Error:
 

     File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
        self.run()
      File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
        self._target(*self._args, **self._kwargs)
      File "test.py", line 9, in myfunc
        engine.runAndWait() #blocks
      File "/usr/local/lib/python3.6/site-packages/pyttsx3/engine.py", line 188, in runAndWait
        self.proxy.runAndWait()
      File "/usr/local/lib/python3.6/site-packages/pyttsx3/driver.py", line 204, in runAndWait
        self._driver.startLoop()
      File "/usr/local/lib/python3.6/site-packages/pyttsx3/drivers/nsss.py", line 33, in startLoop
        AppHelper.runConsoleEventLoop()
      File "/usr/local/lib/python3.6/site-packages/PyObjCTools/AppHelper.py", line 241, in runConsoleEventLoop
        nextfire = nextfire.earlierDate_(soon)
    AttributeError: 'NoneType' object has no attribute 'earlierDate_'

As shown from stack-overflow [replies](https://stackoverflow.com/questions/48025641/how-to-use-pyttsx-in-a-python-thread/48025985#48025985), seem an OSX problem. Can you help me?

**Comment by Kerang** [comment]
Are you using the newest version of pyttsx3? Some error with PyObjC was fixed in the latest version.

https://github.com/nateshmbhat/pyttsx3/issues/1

Also, on that issue:
"
OK! I solve the issue by using 'pip install pyobjc'.  I think this problem is related to the new MacOS Sierra 10.13.1
--
"
Seems like you have pyobjc installed, though.

**Comment by Kerang** [comment]
[Threading problems with OS X](https://github.com/RapidWareTech/pyttsx/issues/7)
and
[Question on use of engine.iterate()](https://github.com/RapidWareTech/pyttsx/issues/11)

May be of use.

**Comment by SqrtPapere** [comment]
Thanks for your interest @Kerang !

I already worked around the problem using this bit of code in thread run method:

```
from subprocess import call
call(["python3", "speak.py", greetings])
```

where speak.py is:
```
import sys
import pyttsx3

def init_engine():
    engine = pyttsx3.init()
    return engine

def say(s):
    engine.say(s)
    engine.runAndWait() #blocks

engine = init_engine()
say(str(sys.argv[1]))
```

I never posted this in the issue because I thought it wasn't a solution, but just a work around. 
Frankly I was waiting for the developers of pyttsx to resolve this problem. I think pyttsx may be the best text-to-speech engine around at the moment and not being able to use it in a OSX thread is a real drawback.

**Comment by Kerang** [comment]
So, you just switched to using a process instead of a thread.

I created a custom class that embeds the pyttsx3 engine into the thread class.
```
# Threading Class
class Threader(Thread):
    def __init__(self, *args, **kwargs):
        Thread.__init__(self, *args, **kwargs)
        self.daemon = True
        self.start()

    def run(self):
        tts_engine = pyttsx3.init()
        tts_engine.say(self._args)
        tts_engine.runAndWait()
```

Which can easily be called like this:
```
self.my_test = "Some text to test"
my_thread = Threader(args=self.my_test)
```

**Comment by Kerang** [comment]
Without an Apple device to test with, I have no way to help. Not sure the maintainer has one either.

I would close the thread, if you've resolved the issue to your satisfaction. Someone could always look at the closed issues, if this is a problem for them.

**Comment by ccarstens** [comment]
> So, you just switched to using a process instead of a thread.
> 
> I created a custom class that overrides the thread class and embeds the pyttsx3 engine.
> 
> ```
> # Threading Class
> class Threader(Thread):
>     def __init__(self, *args, **kwargs):
>         Thread.__init__(self, *args, **kwargs)
>         self.daemon = True
>         self.start()
> 
>     def run(self):
>         tts_engine = pyttsx3.init()
>         tts_engine.say(self._args)
>         tts_engine.runAndWait()
> ```
> 
> Which can easily be called like this:
> 
> ```
> self.my_test = "Some text to test"
> my_thread = Threader(args=self.my_test)
> ```

I tested this solution on macOS 10.14.6 but unfortunately it doesn't work:

I ended up using a Process and a multiprocessing.Queue for making it work.


```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/cornelius/Development/ava/ava/iocthread.py", line 15, in run
    tts_engine.runAndWait()
  File "/Users/cornelius/Development/ava/venv/lib/python3.7/site-packages/pyttsx3/engine.py", line 180, in runAndWait
    self.proxy.runAndWait()
  File "/Users/cornelius/Development/ava/venv/lib/python3.7/site-packages/pyttsx3/driver.py", line 192, in runAndWait
    self._driver.startLoop()
  File "/Users/cornelius/Development/ava/venv/lib/python3.7/site-packages/pyttsx3/drivers/nsss.py", line 35, in startLoop
    AppHelper.runConsoleEventLoop()
  File "/Users/cornelius/Development/ava/venv/lib/python3.7/site-packages/PyObjCTools/AppHelper.py", line 243, in runConsoleEventLoop
    nextfire = nextfire.earlierDate_(soon)
AttributeError: 'NoneType' object has no attribute 'earlierDate_'
```

**Comment by AFUL1991** [comment]
> Thanks for your interest @Kerang !
> 
> I already worked around the problem using this bit of code in thread run method:
> 
> ```
> from subprocess import call
> phrase = "Hi everyone"
> call(["python3", "speak.py", phrase])
> ```
> 
> where speak.py is:
> 
> ```
> import sys
> import pyttsx3
> 
> def init_engine():
>     engine = pyttsx3.init()
>     return engine
> 
> def say(s):
>     engine.say(s)
>     engine.runAndWait() #blocks
> 
> engine = init_engine()
> say(str(sys.argv[1]))
> ```
> 
> I never posted this because I thought it wasn't a solution, but just a work around.
> Frankly I was waiting for the developers of pyttsx to resolve this problem. I think pyttsx may be the best text-to-speech engine around at the moment and not being able to use it in a OSX thread is a real drawback.
> 
> Do you think I should close the issue?

Maybe this is the only way until now

**Comment by jtylka** [comment]
> > So, you just switched to using a process instead of a thread.
> > I created a custom class that overrides the thread class and embeds the pyttsx3 engine.
> > ```
> > # Threading Class
> > class Threader(Thread):
> >     def __init__(self, *args, **kwargs):
> >         Thread.__init__(self, *args, **kwargs)
> >         self.daemon = True
> >         self.start()
> > 
> >     def run(self):
> >         tts_engine = pyttsx3.init()
> >         tts_engine.say(self._args)
> >         tts_engine.runAndWait()
> > ```
> > 
> > 
> > Which can easily be called like this:
> > ```
> > self.my_test = "Some text to test"
> > my_thread = Threader(args=self.my_test)
> > ```
> 
> I tested this solution on macOS 10.14.6 but unfortunately it doesn't work:
> 
> I ended up using a Process and a multiprocessing.Queue for making it work.
> 
> ```
> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
>     self.run()
>   File "/Users/cornelius/Development/ava/ava/iocthread.py", line 15, in run
>     tts_engine.runAndWait()
>   File "/Users/cornelius/Development/ava/venv/lib/python3.7/site-packages/pyttsx3/engine.py", line 180, in runAndWait
>     self.proxy.runAndWait()
>   File "/Users/cornelius/Development/ava/venv/lib/python3.7/site-packages/pyttsx3/driver.py", line 192, in runAndWait
>     self._driver.startLoop()
>   File "/Users/cornelius/Development/ava/venv/lib/python3.7/site-packages/pyttsx3/drivers/nsss.py", line 35, in startLoop
>     AppHelper.runConsoleEventLoop()
>   File "/Users/cornelius/Development/ava/venv/lib/python3.7/site-packages/PyObjCTools/AppHelper.py", line 243, in runConsoleEventLoop
>     nextfire = nextfire.earlierDate_(soon)
> AttributeError: 'NoneType' object has no attribute 'earlierDate_'
> ```

@ccarstens can you provide some code that shows how you made this work using "Process and a multiprocessing.Queue"?

**Comment by ccarstens** [comment]
@jtylka you can check this out:
https://github.com/ccarstens/Ava/blob/dev/ava/environment.py
https://github.com/ccarstens/Ava/blob/dev/ava/iocontroller.py

In environment the process is setup and in iocontroller the strings that should be synthesised using pyttsx are received via the Queue

**Comment by fingoldo** [comment]
> Thanks for your interest @Kerang !
> 
> I already worked around the problem using this bit of code in thread run method:
> 
> ```
> from subprocess import call
> phrase = "Hi everyone"
> call(["python3", "speak.py", phrase])
> ```
> 
> where speak.py is:
> 
> ```
> import sys
> import pyttsx3
> 
> def init_engine():
>     engine = pyttsx3.init()
>     return engine
> 
> def say(s):
>     engine.say(s)
>     engine.runAndWait() #blocks
> 
> engine = init_engine()
> say(str(sys.argv[1]))
> ```
> 
> I never posted this because I thought it wasn't a solution, but just a work around.
> Frankly I was waiting for the developers of pyttsx to resolve this problem. I think pyttsx may be the best text-to-speech engine around at the moment and not being able to use it in a OSX thread is a real drawback.
> 
> Do you think I should close the issue?

I'd rather say Popen instead of call, to make it async.

**Comment by juandres666** [comment]
> @jtylka you can check this out: https://github.com/ccarstens/Ava/blob/dev/ava/environment.py https://github.com/ccarstens/Ava/blob/dev/ava/iocontroller.py
> 
> In environment the process is setup and in iocontroller the strings that should be synthesised using pyttsx are received via the Queue

Hello, Could you resolve this? thanks
