### ISSUE TITLE
How i can change engine from sapi5 to espeak in windows?

### ISSUE THREAD

**Issue by AjaxFB** [nateshmbhat/pyttsx3#85]
How i configure the DLL/ELF load of 'libespeak.so.1' in windows?

I have espeak_sapi.dll and libespeak.so.1 to use.

engine = pyttsx3.init(driverName='espeak')
...
File "C:\Users\User\Documents\scripts\libs\lib\site-packages\pyttsx3\drivers\_espeak.py", line 18, in <module>
    dll = cdll.LoadLibrary('libespeak.so.1')
  File "c:\program files\python37\Lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "c:\program files\python37\Lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] Não foi possível encontrar o módulo especificado

**Comment by nateshmbhat** [comment]
You are in windows . espeak driver is only for linux

**Comment by AjaxFB** [comment]
http://sourceforge.net/projects/espeak/files/espeak/espeak-1.48/setup_espeak-1.48.04.exe
Please, check in website. I think you are wrong

**Comment by nateshmbhat** [comment]
> eSpeak: speech synthesis Overview

Text to Speech engine for English and many other languages. Compact size with clear but artificial pronunciation. Available as a command-line program with many options, a shared library for Linux, and a Windows SAPI5 version.


That website says thus

**Comment by AjaxFB** [comment]
@nateshmbhat ok, no problem :(
