### ISSUE TITLE
Error importing pyttsx3

### ISSUE THREAD

**Issue by kishorekumar45** [nateshmbhat/pyttsx3#86]
I need to submit a project based on this soon, and I have no clue whats going on. I'm really a beginner in coding. It will be nice if anyone could tell me what it says, what should I do.
![Capture](https://user-images.githubusercontent.com/60350055/73178566-92742480-4122-11ea-9c2a-3b9705460961.PNG)

**Comment by AjaxFB** [comment]
@kishorekumar45 Please, see 
https://stackoverflow.com/questions/59913003/while-installing-pyttsx3-over-python-3-8/59917829?noredirect=1#comment105961685_59917829

Use pip install git+https://github.com/nateshmbhat/pyttsx3
