### ISSUE TITLE
install error on Win10

### ISSUE THREAD

**Issue by kathy6606** [nateshmbhat/pyttsx3#93]
C:\Users\Administrator>pip install pyttsx3
Collecting pyttsx3
  Using cached https://files.pythonhosted.org/packages/00/c2/a83636e6ab1db54918cc650b30a409c44d66ebdd6440054674fb948a5b06/pyttsx3-2.80-py3-none-any.whl
Collecting pyobjc>=2.4 (from pyttsx3)
  Using cached https://files.pythonhosted.org/packages/b1/c9/83b256bb7f771a9e4232518005d6f237ae79215283cf5ea234141751b36a/pyobjc-6.1-py3-none-any.whl
Collecting comtypes; "win32" in sys_platform (from pyttsx3)
  Using cached https://files.pythonhosted.org/packages/fb/b8/f8aa21774acb4535e32f6a89055876ca497ff806f9b1b1912b469284a61e/comtypes-1.1.7.zip
Collecting pyobjc-framework-ScreenSaver==6.1 (from pyobjc>=2.4->pyttsx3)
  Downloading https://files.pythonhosted.org/packages/7c/97/c2e1aaaf56b7516640cc3bbd6527e4011f5d867a1ebf5e2f04086d8d1e1d/pyobjc-framework-ScreenSaver-6.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'd:\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-qt_n5lg5\\pyobjc-framework-ScreenSaver\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-qt_n5lg5\\pyobjc-framework-ScreenSaver\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\Administrator\AppData\Local\Temp\pip-install-qt_n5lg5\pyobjc-framework-ScreenSaver\
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Administrator\AppData\Local\Temp\pip-install-qt_n5lg5\pyobjc-framework-ScreenSaver\setup.py", line 19, in <module>
        Extension(
      File "C:\Users\Administrator\AppData\Local\Temp\pip-install-qt_n5lg5\pyobjc-framework-ScreenSaver\pyobjc_setup.py", line 408, in Extension
        os_level = get_os_level()
      File "C:\Users\Administrator\AppData\Local\Temp\pip-install-qt_n5lg5\pyobjc-framework-ScreenSaver\pyobjc_setup.py", line 218, in get_os_level
        pl = plistlib.readPlist("/System/Library/CoreServices/SystemVersion.plist")
      File "d:\python38-32\lib\plistlib.py", line 99, in readPlist
        with _maybe_open(pathOrFile, 'rb') as fp:
      File "d:\python38-32\lib\contextlib.py", line 113, in __enter__
        return next(self.gen)
      File "d:\python38-32\lib\plistlib.py", line 82, in _maybe_open
        with open(pathOrFile, mode) as fp:
    FileNotFoundError: [Errno 2] No such file or directory: '/System/Library/CoreServices/SystemVersion.plist'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

My OS is Win10 and the python version is 3.8，how can I install it successfully？

**Comment by osnipezzini** [comment]
Same problem here

**Comment by nateshmbhat** [comment]
I have updated the package on Pypi . can u try installing now ?

**Comment by kathy6606** [comment]
Yes, I have installed it. Thank you ~ :)
