### ISSUE TITLE
python 3.8 

### ISSUE THREAD

**Issue by Rajendro1** [nateshmbhat/pyttsx3#97]
Traceback (most recent call last):
  File "C:/Users/Lenovo/Desktop/jarves.py", line 2, in <module>
    import pyttsx3
ModuleNotFoundError: No module named 'pyttsx3'

**Comment by 01010000-kumar** [comment]
install the library using `pip install pyttsx3`

**Comment by Rajendro1** [comment]
I already install it.

**Comment by nateshmbhat** [comment]
The latest pyttsx3 release fixes this
